/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountDetectAccount } from "../../funcs/accountDetectAccount.js";
import { DetectAccountRequest$zodSchema } from "../../models/detectaccountop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DetectAccountRequest$zodSchema,
};

export const tool$accountDetectAccount: ToolDefinition<typeof args> = {
  name: "account-detect-account",
  description: `Detect Account

Check whether an account exists using one of \`email\`, \`phone\`, or \`sha256_email\` as the unique identifier.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await accountDetectAccount(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
