/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { configurationGetMerchantCallbacks } from "../../funcs/configurationGetMerchantCallbacks.js";
import { GetMerchantCallbacksRequest$zodSchema } from "../../models/getmerchantcallbacksop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetMerchantCallbacksRequest$zodSchema,
};

export const tool$configurationGetMerchantCallbacks: ToolDefinition<
  typeof args
> = {
  name: "configuration-get-merchant-callbacks",
  description: `Get Callback URLs

Retrieves callbacks URLs for a Bolt merchant division.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await configurationGetMerchantCallbacks(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
