/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { configurationGetMerchantIdentifiers } from "../../funcs/configurationGetMerchantIdentifiers.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$configurationGetMerchantIdentifiers: ToolDefinition = {
  name: "configuration-get-merchant-identifiers",
  description: `Get Merchant Identifiers

This endpoint returns the merchant's public ID and the [publishable key](https://help.bolt.com/developers/tools/api-keys/) related to the merchant division.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await configurationGetMerchantIdentifiers(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
