/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { configurationSetMerchantCallbacks } from "../../funcs/configurationSetMerchantCallbacks.js";
import { MerchantCallbacksInput$zodSchema } from "../../models/merchantcallbacksinput.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: MerchantCallbacksInput$zodSchema.optional(),
};

export const tool$configurationSetMerchantCallbacks: ToolDefinition<
  typeof args
> = {
  name: "configuration-set-merchant-callbacks",
  description: `Set Callback URLs

Configure callbacks URLs for a Bolt merchant division. This will store or override only the callback URLs that are specified in the request. Operations are fully transactional.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await configurationSetMerchantCallbacks(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
