/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ordersTrackOrder } from "../../funcs/ordersTrackOrder.js";
import { OrderTrackRequestBody$zodSchema } from "../../models/ordertrackrequestbody.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: OrderTrackRequestBody$zodSchema.optional(),
};

export const tool$ordersTrackOrder: ToolDefinition<typeof args> = {
  name: "orders-track-order",
  description: `Send order tracking details

Send the carrier and order tracking number to Bolt (after a label has been printed). Bolt then uses EasyPost to forward ongoing tracking event updates to the shopper. This request must include **all** items included in the shipment; their references must also match those found in the original cart generation.
`,
  annotations: {
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await ordersTrackOrder(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
