/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ordersCreateOrderToken } from "../../funcs/ordersCreateOrderToken.js";
import { OrderCreate$zodSchema } from "../../models/ordercreate.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: OrderCreate$zodSchema.optional(),
};

export const tool$ordersCreateOrderToken: ToolDefinition<typeof args> = {
  name: "orders-create-order-token",
  description: `Create Order Token

Make a request to this endpoint to create a Bolt order, generate a Bolt order token, and initiate the checkout process. A Bolt order token is required for Bolt orders; see Non-Bolt orders for alternative use cases.`,
  annotations: {
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await ordersCreateOrderToken(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
