/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { statementsGetStatements } from "../../funcs/statementsGetStatements.js";
import { StatementsViewRequestBody$zodSchema } from "../../models/statementsviewrequestbody.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: StatementsViewRequestBody$zodSchema.optional(),
};

export const tool$statementsGetStatements: ToolDefinition<typeof args> = {
  name: "statements-get-statements",
  description: `Fetch a Statement

Get a pre-signed URL for the requested statement file.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await statementsGetStatements(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
