/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { testingTestShipping } from "../../funcs/testingTestShipping.js";
import { MockTrackingInput$zodSchema } from "../../models/mocktrackinginput.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: MockTrackingInput$zodSchema.optional(),
};

export const tool$testingTestShipping: ToolDefinition<typeof args> = {
  name: "testing-test-shipping",
  description: `Test Shipping

This endpoint simulates tracking an order's shipment and is for testing purposes only.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await testingTestShipping(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
