/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { testingGetTestCreditCardToken } from "../../funcs/testingGetTestCreditCardToken.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$testingGetTestCreditCardToken: ToolDefinition = {
  name: "testing-get-test-credit-card-token",
  description: `Fetch a Test Credit Card Token

This endpoint fetches a new credit card token for Bolt's universal test credit card number \`4111 1111 1111 1004\`. This is for testing and is available only in sandbox.`,
  annotations: {
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  tool: async (client, ctx) => {
    const [result, apiCall] = await testingGetTestCreditCardToken(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
