/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { transactionsGetTransactionDetails } from "../../funcs/transactionsGetTransactionDetails.js";
import { GetTransactionDetailsRequest$zodSchema } from "../../models/gettransactiondetailsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetTransactionDetailsRequest$zodSchema,
};

export const tool$transactionsGetTransactionDetails: ToolDefinition<
  typeof args
> = {
  name: "transactions-get-transaction-details",
  description: `Transaction Details

This allows you to pull the full transaction details for a given transaction.

 **Note**: All objects and fields marked \`required\` in the Transaction Details response are also **nullable**. This includes any sub-components (objects or fields) also marked \`required\`.
`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await transactionsGetTransactionDetails(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
