/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { transactionsUpdateTransaction } from "../../funcs/transactionsUpdateTransaction.js";
import { UpdateTransactionRequest$zodSchema } from "../../models/updatetransactionop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateTransactionRequest$zodSchema,
};

export const tool$transactionsUpdateTransaction: ToolDefinition<typeof args> = {
  name: "transactions-update-transaction",
  description: `Update a Transaction

This allows you to update certain transaction properties post-authorization.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await transactionsUpdateTransaction(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
