/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { transactionsReviewTransaction } from "../../funcs/transactionsReviewTransaction.js";
import { ReviewTransactionRequest$zodSchema } from "../../models/reviewtransactionop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ReviewTransactionRequest$zodSchema.optional(),
};

export const tool$transactionsReviewTransaction: ToolDefinition<typeof args> = {
  name: "transactions-review-transaction",
  description: `Review Transaction

This endpoint is used to manually approve or reject orders for a specified transaction.`,
  annotations: {
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await transactionsReviewTransaction(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
