/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksDeleteWebhook } from "../../funcs/webhooksDeleteWebhook.js";
import { DeleteWebhookRequest$zodSchema } from "../../models/deletewebhookop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteWebhookRequest$zodSchema,
};

export const tool$webhooksDeleteWebhook: ToolDefinition<typeof args> = {
  name: "webhooks-delete-webhook",
  description: `Delete a Bolt Webhook

Delete a Bolt webhook. Provide an authorized X-API-Key to perform this action.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await webhooksDeleteWebhook(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
