/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksGetWebhook } from "../../funcs/webhooksGetWebhook.js";
import { GetWebhookRequest$zodSchema } from "../../models/getwebhookop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetWebhookRequest$zodSchema,
};

export const tool$webhooksGetWebhook: ToolDefinition<typeof args> = {
  name: "webhooks-get-webhook",
  description: `Get Webhook

Get Webhook information by its Webhook ID. Results only include webhooks authorized by the X-API-Key.`,
  annotations: {
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await webhooksGetWebhook(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
