/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksCreateWebhook } from "../../funcs/webhooksCreateWebhook.js";
import { CreateWebhookRequest$zodSchema } from "../../models/createwebhookop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateWebhookRequest$zodSchema,
};

export const tool$webhooksCreateWebhook: ToolDefinition<typeof args> = {
  name: "webhooks-create-webhook",
  description: `Create Bolt Webhook

Create a new webhook to receive notifications from Bolt about various events, such as transaction status. Webhooks must have unique configuration.`,
  annotations: {
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await webhooksCreateWebhook(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
