/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksQueryWebhooks } from "../../funcs/webhooksQueryWebhooks.js";
import { QueryWebhooksRequest$zodSchema } from "../../models/querywebhooksop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: QueryWebhooksRequest$zodSchema,
};

export const tool$webhooksQueryWebhooks: ToolDefinition<typeof args> = {
  name: "webhooks-query-webhooks",
  description: `Query Webhooks

Find webhook configurations belonging to a merchant division. Results are limited to only show webhooks authorized by the X-API-Key.`,
  annotations: {
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await webhooksQueryWebhooks(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
