/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The status of the shopper account identifier (email or phone). If the account does not have this identifier, the status is "missing"; If the identifier has been used to receive an OTP code, the status is "verified"; If the identifier has not been used to receive an OTP code, the status is "unverified".
 */
export const AccountIdentifierStatus$zodSchema = z.enum([
  "missing",
  "verified",
  "unverified",
]).describe(
  "The status of the shopper account identifier (email or phone). If the account does not have this identifier, the status is \"missing\"; If the identifier has been used to receive an OTP code, the status is \"verified\"; If the identifier has not been used to receive an OTP code, the status is \"unverified\".",
);

export type AccountIdentifierStatus = z.infer<
  typeof AccountIdentifierStatus$zodSchema
>;
