/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AddressChangeRequestMetadataView = {
  can_change_shipping_address?: boolean | undefined;
  id?: string | undefined;
  status?: string | undefined;
  ticket_id?: string | undefined;
  ticket_status?: string | undefined;
};

export const AddressChangeRequestMetadataView$zodSchema: z.ZodType<
  AddressChangeRequestMetadataView,
  z.ZodTypeDef,
  unknown
> = z.object({
  can_change_shipping_address: z.boolean().optional(),
  id: z.string().optional(),
  status: z.string().optional(),
  ticket_id: z.string().optional(),
  ticket_status: z.string().optional(),
});
