/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The shopper-indicated priority of this address compared to other addresses on their account.
 */
export const AddressViewPriority$zodSchema = z.enum([
  "primary",
  "listed",
]).describe(
  "The shopper-indicated priority of this address compared to other addresses on their account.",
);

export type AddressViewPriority = z.infer<typeof AddressViewPriority$zodSchema>;

/**
 * The address object returned in the response.
 */
export type AddressView = {
  company?: string | undefined;
  country?: string | undefined;
  country_code?: string | undefined;
  door_code?: string | null | undefined;
  email_address?: string | undefined;
  first_name?: string | undefined;
  id?: string | undefined;
  last_name?: string | undefined;
  locality?: string | undefined;
  name?: string | undefined;
  phone_number?: string | undefined;
  postal_code?: string | undefined;
  priority?: AddressViewPriority | null | undefined;
  region?: string | undefined;
  region_code?: string | null | undefined;
  street_address1?: string | undefined;
  street_address2?: string | undefined;
  street_address3?: string | null | undefined;
  street_address4?: string | null | undefined;
};

export const AddressView$zodSchema: z.ZodType<
  AddressView,
  z.ZodTypeDef,
  unknown
> = z.object({
  company: z.string().optional(),
  country: z.string().optional(),
  country_code: z.string().optional(),
  door_code: z.string().nullable().optional(),
  email_address: z.string().optional(),
  first_name: z.string().optional(),
  id: z.string().optional(),
  last_name: z.string().optional(),
  locality: z.string().optional(),
  name: z.string().optional(),
  phone_number: z.string().optional(),
  postal_code: z.string().optional(),
  priority: AddressViewPriority$zodSchema.nullable().optional(),
  region: z.string().optional(),
  region_code: z.string().nullable().optional(),
  street_address1: z.string().optional(),
  street_address2: z.string().optional(),
  street_address3: z.string().nullable().optional(),
  street_address4: z.string().nullable().optional(),
}).describe("The address object returned in the response.");
