/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ShopperMetadata,
  ShopperMetadata$zodSchema,
} from "./shoppermetadata.js";

/**
 * The Address object is used for billing, shipping, and physical store address use cases.
 */
export type AddressAccount = {
  company?: string | undefined;
  country?: string | undefined;
  country_code: string;
  default?: boolean | undefined;
  door_code?: string | null | undefined;
  email: string;
  first_name: string;
  last_name: string;
  locality: string;
  name?: string | undefined;
  phone?: string | undefined;
  postal_code: string;
  region: string;
  region_code?: string | null | undefined;
  street_address1: string;
  street_address2?: string | undefined;
  street_address3?: string | null | undefined;
  street_address4?: string | null | undefined;
  metadata?: ShopperMetadata | null | undefined;
};

export const AddressAccount$zodSchema: z.ZodType<
  AddressAccount,
  z.ZodTypeDef,
  unknown
> = z.object({
  company: z.string().optional(),
  country: z.string().optional(),
  country_code: z.string(),
  default: z.boolean().optional(),
  door_code: z.string().nullable().optional(),
  email: z.string(),
  first_name: z.string(),
  last_name: z.string(),
  locality: z.string(),
  metadata: ShopperMetadata$zodSchema.nullable().optional(),
  name: z.string().optional(),
  phone: z.string().optional(),
  postal_code: z.string(),
  region: z.string(),
  region_code: z.string().nullable().optional(),
  street_address1: z.string(),
  street_address2: z.string().optional(),
  street_address3: z.string().nullable().optional(),
  street_address4: z.string().nullable().optional(),
}).describe(
  "The Address object is used for billing, shipping, and physical store address use cases.",
);
