/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AddressView, AddressView$zodSchema } from "./addressview.js";

export type AddressChangeView = {
  from_address?: AddressView | undefined;
  status?: string | undefined;
  ticket_id?: string | undefined;
  timestamp?: number | undefined;
  to_address?: AddressView | undefined;
};

export const AddressChangeView$zodSchema: z.ZodType<
  AddressChangeView,
  z.ZodTypeDef,
  unknown
> = z.object({
  from_address: AddressView$zodSchema.optional(),
  status: z.string().optional(),
  ticket_id: z.string().optional(),
  timestamp: z.number().optional(),
  to_address: AddressView$zodSchema.optional(),
});
