/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The amount. **Nullable** for Transactions Details.
 */
export type Amounts = {
  amount: number;
  currency: string;
  currency_symbol: string;
};

export const Amounts$zodSchema: z.ZodType<Amounts, z.ZodTypeDef, unknown> = z
  .object({
    amount: z.number().int(),
    currency: z.string(),
    currency_symbol: z.string(),
  }).describe("The amount. **Nullable** for Transactions Details.");
