/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AmountView = {
  amount?: number | undefined;
  currency?: string | undefined;
  currency_symbol?: string | undefined;
};

export const AmountView$zodSchema: z.ZodType<
  AmountView,
  z.ZodTypeDef,
  unknown
> = z.object({
  amount: z.number().optional(),
  currency: z.string().optional(),
  currency_symbol: z.string().optional(),
});
