/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Used to track the status of micro-authorizations. **Nullable** for Transactions Details.
 */
export const AuthorizationVerificationStatus$zodSchema = z.enum([
  "new",
  "verified",
  "failed",
  "expired",
]).describe(
  "Used to track the status of micro-authorizations. **Nullable** for Transactions Details. ",
);

export type AuthorizationVerificationStatus = z.infer<
  typeof AuthorizationVerificationStatus$zodSchema
>;
