/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AuthRejectionDetails = {
  reason_code?: string | undefined;
  reason_description?: string | undefined;
};

export const AuthRejectionDetails$zodSchema: z.ZodType<
  AuthRejectionDetails,
  z.ZodTypeDef,
  unknown
> = z.object({
  reason_code: z.string().optional(),
  reason_description: z.string().optional(),
});
