/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AuthRejectionDetailsView = {
  reason_code?: string | undefined;
  reason_description: string;
};

export const AuthRejectionDetailsView$zodSchema: z.ZodType<
  AuthRejectionDetailsView,
  z.ZodTypeDef,
  unknown
> = z.object({
  reason_code: z.string().optional(),
  reason_description: z.string(),
});
