/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The status of the capture. **Nullable** for Transactions Details.
 */
export const CaptureStatus$zodSchema = z.enum([
  "succeeded",
  "declined",
  "error",
]).describe(
  "The status of the capture. **Nullable** for Transactions Details.",
);

export type CaptureStatus = z.infer<typeof CaptureStatus$zodSchema>;
