/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Capture a Transaction
 */
export type CaptureTransactionWithReference = {
  amount: number;
  currency: string;
  merchant_event_id?: string | undefined;
  skip_hook_notification?: boolean | undefined;
  transaction_reference: string;
};

export const CaptureTransactionWithReference$zodSchema: z.ZodType<
  CaptureTransactionWithReference,
  z.ZodTypeDef,
  unknown
> = z.object({
  amount: z.number().int(),
  currency: z.string(),
  merchant_event_id: z.string().optional(),
  skip_hook_notification: z.boolean().optional(),
  transaction_reference: z.string(),
}).describe("Capture a Transaction");
