/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The card's network code. **Nullable** for Transactions Details. Note: LEGACY diners_club_us_ca now tagged as mastercard
 *
 * @remarks
 */
export const CardNetwork$zodSchema = z.enum([
  "visa",
  "mastercard",
  "amex",
  "discover",
  "dinersclub",
  "jcb",
  "unionpay",
  "alliancedata",
  "citiplcc",
  "unknown",
]).describe(
  "The card's network code. **Nullable** for Transactions Details. Note: LEGACY diners_club_us_ca now tagged as mastercard\n"
    + "",
);

export type CardNetwork = z.infer<typeof CardNetwork$zodSchema>;
