/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The card's network. **Nullable** for Transactions Details.
 */
export const CardDisplayNetwork$zodSchema = z.enum([
  "Credit Card",
  "American Express",
  "Diners Club",
  "Discover",
  "JCB",
  "MasterCard",
  "Union Pay",
  "Visa",
]).describe("The card's network. **Nullable** for Transactions Details.");

export type CardDisplayNetwork = z.infer<typeof CardDisplayNetwork$zodSchema>;
