/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Used to define which payment processor generated the token for this credit card.
 *
 * @remarks
 */
export const CardTokenType$zodSchema = z.enum([
  "vantiv",
  "applepay",
  "bolt",
  "stripe",
  "plcc",
  "applepay_encrypted_blob",
]).describe(
  "Used to define which payment processor generated the token for this credit card.\n"
    + "",
);

export type CardTokenType = z.infer<typeof CardTokenType$zodSchema>;
