/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The card's status. **Nullable** for Transactions Details.
 */
export const CardStatus$zodSchema = z.enum([
  "active",
  "created",
  "inactive",
  "transient",
]).describe("The card's status. **Nullable** for Transactions Details.");

export type CardStatus = z.infer<typeof CardStatus$zodSchema>;
