/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CartItemProperty = {
  color?: string | undefined;
  display?: boolean | undefined;
  name?: string | undefined;
  name_id?: number | undefined;
  value?: string | undefined;
  value_id?: number | undefined;
};

export const CartItemProperty$zodSchema: z.ZodType<
  CartItemProperty,
  z.ZodTypeDef,
  unknown
> = z.object({
  color: z.string().optional(),
  display: z.boolean().optional(),
  name: z.string().optional(),
  name_id: z.number().optional(),
  value: z.string().optional(),
  value_id: z.number().optional(),
});
