/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AmountView, AmountView$zodSchema } from "./amountview.js";

export type CartLoyaltyRewardsView = {
  amount?: AmountView | undefined;
  coupon_code?: string | undefined;
  description?: string | undefined;
  details?: string | undefined;
  points?: number | undefined;
  source?: string | undefined;
  type?: string | undefined;
};

export const CartLoyaltyRewardsView$zodSchema: z.ZodType<
  CartLoyaltyRewardsView,
  z.ZodTypeDef,
  unknown
> = z.object({
  amount: AmountView$zodSchema.optional(),
  coupon_code: z.string().optional(),
  description: z.string().optional(),
  details: z.string().optional(),
  points: z.number().int().optional(),
  source: z.string().optional(),
  type: z.string().optional(),
});
