/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CartFee = {
  reference: string;
  name: string | null;
  description?: string | null | undefined;
  unit_price: number;
  unit_tax_amount: number;
  quantity: number;
};

export const CartFee$zodSchema: z.ZodType<CartFee, z.ZodTypeDef, unknown> = z
  .object({
    description: z.string().nullable().optional(),
    name: z.string().nullable(),
    quantity: z.number(),
    reference: z.string(),
    unit_price: z.number(),
    unit_tax_amount: z.number(),
  });
