/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CartLoyaltyRewards = {
  amount?: number | undefined;
  coupon_code?: string | undefined;
  description?: string | undefined;
  details?: string | undefined;
  points?: number | undefined;
  source?: string | undefined;
  type?: string | undefined;
};

export const CartLoyaltyRewards$zodSchema: z.ZodType<
  CartLoyaltyRewards,
  z.ZodTypeDef,
  unknown
> = z.object({
  amount: z.number().optional(),
  coupon_code: z.string().optional(),
  description: z.string().optional(),
  details: z.string().optional(),
  points: z.number().optional(),
  source: z.string().optional(),
  type: z.string().optional(),
});
