/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * A list of up to 3 add-ons that are displayed to the shopper.
 */
export type CartAddOn = {
  description?: string | undefined;
  imageUrl?: string | undefined;
  name: string;
  price: number;
  productId: string;
  productPageUrl?: string | undefined;
};

export const CartAddOn$zodSchema: z.ZodType<CartAddOn, z.ZodTypeDef, unknown> =
  z.object({
    description: z.string().optional(),
    imageUrl: z.string().optional(),
    name: z.string(),
    price: z.number(),
    productId: z.string(),
    productPageUrl: z.string().optional(),
  }).describe("A list of up to 3 add-ons that are displayed to the shopper.");
