/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The type corresponding to this shipment, if applicable.
 */
export const CartShipmentType$zodSchema = z.enum([
  "door_delivery",
  "in_store_pickup",
  "ship_to_store",
  "ship_to_home_only",
  "unknown",
]).describe("The type corresponding to this shipment, if applicable.");

export type CartShipmentType = z.infer<typeof CartShipmentType$zodSchema>;
