/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Contains the gift option settings for wrapping and custom messages.
 */
export type CartItemGiftOption = {
  cost?: number | undefined;
  merchant_product_id?: string | undefined;
  message?: string | undefined;
  wrap?: boolean | undefined;
};

export const CartItemGiftOption$zodSchema: z.ZodType<
  CartItemGiftOption,
  z.ZodTypeDef,
  unknown
> = z.object({
  cost: z.number().int().optional(),
  merchant_product_id: z.string().optional(),
  message: z.string().optional(),
  wrap: z.boolean().optional(),
}).describe(
  "Contains the gift option settings for wrapping and custom messages.",
);
