/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CartItemPropertyView = {
  color?: string | undefined;
  display?: boolean | undefined;
  name?: string | undefined;
  value?: string | undefined;
};

export const CartItemPropertyView$zodSchema: z.ZodType<
  CartItemPropertyView,
  z.ZodTypeDef,
  unknown
> = z.object({
  color: z.string().optional(),
  display: z.boolean().optional(),
  name: z.string().optional(),
  value: z.string().optional(),
});
