/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CartItemCustomization = {
  attributes?: { [k: string]: string } | undefined;
  name?: string | undefined;
  price?: number | undefined;
};

export const CartItemCustomization$zodSchema: z.ZodType<
  CartItemCustomization,
  z.ZodTypeDef,
  unknown
> = z.object({
  attributes: z.record(z.string()).optional(),
  name: z.string().optional(),
  price: z.number().optional(),
});
