/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Address, Address$zodSchema } from "./address.js";
import {
  CartShipmentType,
  CartShipmentType$zodSchema,
} from "./cartshipmenttype.js";

/**
 * A cart that is being prepared for shipment
 */
export type CartShipment = {
  carrier?: string | undefined;
  cost?: number | undefined;
  discounted_by_membership?: boolean | undefined;
  estimated_delivery_date?: string | undefined;
  expedited?: boolean | undefined;
  package_depth?: number | undefined;
  package_dimension_unit?: string | undefined;
  package_height?: number | undefined;
  package_type?: string | undefined;
  package_weight_unit?: string | undefined;
  package_width?: number | undefined;
  service?: string | undefined;
  shipping_address?: Address | undefined;
  shipping_address_id?: string | undefined;
  shipping_method?: string | undefined;
  signature?: string | undefined;
  tax_amount?: number | undefined;
  tax_code?: string | undefined;
  total_weight?: number | undefined;
  total_weight_unit?: string | undefined;
  type?: CartShipmentType | undefined;
};

export const CartShipment$zodSchema: z.ZodType<
  CartShipment,
  z.ZodTypeDef,
  unknown
> = z.object({
  carrier: z.string().optional(),
  cost: z.number().int().optional(),
  discounted_by_membership: z.boolean().optional(),
  estimated_delivery_date: z.string().optional(),
  expedited: z.boolean().optional(),
  package_depth: z.number().int().optional(),
  package_dimension_unit: z.string().optional(),
  package_height: z.number().int().optional(),
  package_type: z.string().optional(),
  package_weight_unit: z.string().optional(),
  package_width: z.number().int().optional(),
  service: z.string().optional(),
  shipping_address: Address$zodSchema.optional(),
  shipping_address_id: z.string().optional(),
  shipping_method: z.string().optional(),
  signature: z.string().optional(),
  tax_amount: z.number().int().optional(),
  tax_code: z.string().optional(),
  total_weight: z.number().int().optional(),
  total_weight_unit: z.string().optional(),
  type: CartShipmentType$zodSchema.optional(),
}).describe("A cart that is being prepared for shipment");
