/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AddressView, AddressView$zodSchema } from "./addressview.js";
import { AmountView, AmountView$zodSchema } from "./amountview.js";
import {
  CartLoyaltyRewardsView,
  CartLoyaltyRewardsView$zodSchema,
} from "./cartloyaltyrewardsview.js";
import {
  FulfillmentView,
  FulfillmentView$zodSchema,
} from "./fulfillmentview.js";
import {
  ICartDiscountView,
  ICartDiscountView$zodSchema,
} from "./icartdiscountview.js";
import { ICartItemView, ICartItemView$zodSchema } from "./icartitemview.js";
import {
  ICartShipmentView,
  ICartShipmentView$zodSchema,
} from "./icartshipmentview.js";
import { ICurrency, ICurrency$zodSchema } from "./icurrency.js";
import {
  InStoreShipment2,
  InStoreShipment2$zodSchema,
} from "./instoreshipment2.js";

/**
 * This is the cart object returned in a successful response.
 */
export type CartView = {
  billing_address?: AddressView | undefined;
  cart_url?: string | undefined;
  currency?: ICurrency | undefined;
  discount_amount?: AmountView | undefined;
  discounts?: Array<ICartDiscountView> | undefined;
  display_id?: string | undefined;
  fee_amount?: AmountView | undefined;
  fees?: Array<ICartItemView> | undefined;
  fulfillments?: Array<FulfillmentView> | undefined;
  in_store_shipments?: InStoreShipment2 | undefined;
  items?: Array<ICartItemView> | undefined;
  loyalty_rewards?: Array<CartLoyaltyRewardsView> | undefined;
  loyalty_rewards_amount?: AmountView | undefined;
  merchant_order_url?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  msrp?: AmountView | undefined;
  order_description?: string | undefined;
  order_reference?: string | undefined;
  shipments?: Array<ICartShipmentView> | undefined;
  shipping_amount?: AmountView | undefined;
  subtotal_amount?: AmountView | undefined;
  tax_amount?: AmountView | undefined;
  total_amount?: AmountView | undefined;
  transaction_reference?: string | undefined;
};

export const CartView$zodSchema: z.ZodType<CartView, z.ZodTypeDef, unknown> = z
  .object({
    billing_address: AddressView$zodSchema.optional(),
    cart_url: z.string().optional(),
    currency: ICurrency$zodSchema.optional(),
    discount_amount: AmountView$zodSchema.optional(),
    discounts: z.array(ICartDiscountView$zodSchema).optional(),
    display_id: z.string().optional(),
    fee_amount: AmountView$zodSchema.optional(),
    fees: z.array(ICartItemView$zodSchema).optional(),
    fulfillments: z.array(FulfillmentView$zodSchema).optional(),
    in_store_shipments: InStoreShipment2$zodSchema.optional(),
    items: z.array(ICartItemView$zodSchema).optional(),
    loyalty_rewards: z.array(CartLoyaltyRewardsView$zodSchema).optional(),
    loyalty_rewards_amount: AmountView$zodSchema.optional(),
    merchant_order_url: z.string().optional(),
    metadata: z.record(z.string()).optional(),
    msrp: AmountView$zodSchema.optional(),
    order_description: z.string().optional(),
    order_reference: z.string().optional(),
    shipments: z.array(ICartShipmentView$zodSchema).optional(),
    shipping_amount: AmountView$zodSchema.optional(),
    subtotal_amount: AmountView$zodSchema.optional(),
    tax_amount: AmountView$zodSchema.optional(),
    total_amount: AmountView$zodSchema.optional(),
    transaction_reference: z.string().optional(),
  }).describe("This is the cart object returned in a successful response.");
