/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const CartDiscountDiscountCategory$zodSchema = z.enum([
  "coupon",
  "giftcard",
  "managed_giftcard",
  "store_credit",
  "automatic_promotion",
  "membership_discount",
  "membership_giftcard",
  "subscription_discount",
  "rewards_discount",
  "unknown",
]);

export type CartDiscountDiscountCategory = z.infer<
  typeof CartDiscountDiscountCategory$zodSchema
>;

/**
 * The type of discount.
 */
export const CartDiscountType$zodSchema = z.enum([
  "fixed_amount",
  "percentage",
  "free_shipping",
]).describe("The type of discount.");

export type CartDiscountType = z.infer<typeof CartDiscountType$zodSchema>;

export type CartDiscount = {
  amount?: number | undefined;
  code?: string | undefined;
  description?: string | undefined;
  details_url?: string | undefined;
  discount_category?: CartDiscountDiscountCategory | undefined;
  reference?: string | undefined;
  type?: CartDiscountType | undefined;
};

export const CartDiscount$zodSchema: z.ZodType<
  CartDiscount,
  z.ZodTypeDef,
  unknown
> = z.object({
  amount: z.number().optional(),
  code: z.string().optional(),
  description: z.string().optional(),
  details_url: z.string().optional(),
  discount_category: CartDiscountDiscountCategory$zodSchema.optional(),
  reference: z.string().optional(),
  type: CartDiscountType$zodSchema.optional(),
});
