/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Bolt's [standardized reason codes](https://help.bolt.com/merchants/references/policies/disputes/dispute-codes/).
 */
export const ChargebackReasonCode$zodSchema = z.enum([
  "authorization_failed",
  "cancelled_recurring",
  "cardholder_dispute",
  "currency_error",
  "duplicate",
  "fraud_general",
  "fraud_no_authorization",
  "incorrect_amount",
  "late_presentment",
  "processing_error",
  "processor_general",
  "product_defective",
  "product_not_received",
  "product_returned",
  "request_for_information",
]).describe(
  "Bolt's [standardized reason codes](https://help.bolt.com/merchants/references/policies/disputes/dispute-codes/).",
);

export type ChargebackReasonCode = z.infer<
  typeof ChargebackReasonCode$zodSchema
>;
