/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AmountView, AmountView$zodSchema } from "./amountview.js";
import {
  ChargebackEventView,
  ChargebackEventView$zodSchema,
} from "./chargebackeventview.js";
import {
  ChargebackReasonCode,
  ChargebackReasonCode$zodSchema,
} from "./chargebackreasoncode.js";
import {
  ChargebackRepresentmentResult,
  ChargebackRepresentmentResult$zodSchema,
} from "./chargebackrepresentmentresult.js";

export type ChargebackDetails = {
  amt_won?: AmountView | undefined;
  chargeback_amt?: AmountView | undefined;
  chargeback_fee?: AmountView | undefined;
  chargeback_id?: string | undefined;
  event_views?: Array<ChargebackEventView> | undefined;
  net_amt?: AmountView | undefined;
  reason?: string | undefined;
  reason_code?: ChargebackReasonCode | undefined;
  representment_reply_by_date?: number | undefined;
  representment_result?: ChargebackRepresentmentResult | undefined;
};

export const ChargebackDetails$zodSchema: z.ZodType<
  ChargebackDetails,
  z.ZodTypeDef,
  unknown
> = z.object({
  amt_won: AmountView$zodSchema.optional(),
  chargeback_amt: AmountView$zodSchema.optional(),
  chargeback_fee: AmountView$zodSchema.optional(),
  chargeback_id: z.string().optional(),
  event_views: z.array(ChargebackEventView$zodSchema).optional(),
  net_amt: AmountView$zodSchema.optional(),
  reason: z.string().optional(),
  reason_code: ChargebackReasonCode$zodSchema.optional(),
  representment_reply_by_date: z.number().int().optional(),
  representment_result: ChargebackRepresentmentResult$zodSchema.optional(),
});
