/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The result of the chargeback representment.
 */
export const ChargebackRepresentmentResult$zodSchema = z.enum([
  "none",
  "open",
  "lost",
  "won",
]).describe("The result of the chargeback representment.");

export type ChargebackRepresentmentResult = z.infer<
  typeof ChargebackRepresentmentResult$zodSchema
>;
