/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ChargebackEventView = {
  content?: string | undefined;
  time?: number | undefined;
};

export const ChargebackEventView$zodSchema: z.ZodType<
  ChargebackEventView,
  z.ZodTypeDef,
  unknown
> = z.object({
  content: z.string().optional(),
  time: z.number().optional(),
});
