/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ConsumerSummaryView = {
  first_name?: string | undefined;
  id?: string | undefined;
  last_name?: string | undefined;
};

export const ConsumerSummaryView$zodSchema: z.ZodType<
  ConsumerSummaryView,
  z.ZodTypeDef,
  unknown
> = z.object({
  first_name: z.string().optional(),
  id: z.string().optional(),
  last_name: z.string().optional(),
});
