/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ConsumerBillingAddress = {
  company?: string | undefined;
  country?: string | undefined;
  country_code?: string | undefined;
  email_address?: string | undefined;
  first_name?: string | undefined;
  id?: string | null | undefined;
  last_name?: string | undefined;
  locality: string;
  name?: string | undefined;
  phone_number?: string | undefined;
  postal_code: string;
  region: string;
  street_address1: string;
  street_address2?: string | undefined;
  street_address3?: string | undefined;
  street_address4?: string | undefined;
};

export const ConsumerBillingAddress$zodSchema: z.ZodType<
  ConsumerBillingAddress,
  z.ZodTypeDef,
  unknown
> = z.object({
  company: z.string().optional(),
  country: z.string().optional(),
  country_code: z.string().optional(),
  email_address: z.string().optional(),
  first_name: z.string().optional(),
  id: z.string().nullable().optional(),
  last_name: z.string().optional(),
  locality: z.string(),
  name: z.string().optional(),
  phone_number: z.string().optional(),
  postal_code: z.string(),
  region: z.string(),
  street_address1: z.string(),
  street_address2: z.string().optional(),
  street_address3: z.string().optional(),
  street_address4: z.string().optional(),
});
