/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * True if user has an AllPass membership associated to their Bolt Account. **Nullable** for Transactions Details.
 */
export const ConsumerMembershipStatus$zodSchema = z.enum([
  "active",
  "cancelled",
  "disabled",
  "free_trial",
]).describe(
  "True if user has an AllPass membership associated to their Bolt Account. **Nullable** for Transactions Details.",
);

export type ConsumerMembershipStatus = z.infer<
  typeof ConsumerMembershipStatus$zodSchema
>;
