/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ConsumerMembershipStatus,
  ConsumerMembershipStatus$zodSchema,
} from "./consumermembershipstatus.js";

/**
 * **Nullable** for Transactions Details.
 *
 * @remarks
 */
export type ConsumerUserMembership = { status: ConsumerMembershipStatus };

export const ConsumerUserMembership$zodSchema: z.ZodType<
  ConsumerUserMembership,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: ConsumerMembershipStatus$zodSchema,
}).describe(
  "**Nullable** for Transactions Details.\n"
    + "",
);
