/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ErrorsBoltApiResponse,
  ErrorsBoltApiResponse$zodSchema,
} from "./errorsboltapiresponse.js";
import { IOrderView, IOrderView$zodSchema } from "./iorderview.js";

export type CreateOrderTokenResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  i_order_view?: IOrderView | undefined;
  errors_bolt_api_response?: ErrorsBoltApiResponse | undefined;
};

export const CreateOrderTokenResponse$zodSchema: z.ZodType<
  CreateOrderTokenResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  errors_bolt_api_response: ErrorsBoltApiResponse$zodSchema.optional(),
  i_order_view: IOrderView$zodSchema.optional(),
});
