/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AddressAccount, AddressAccount$zodSchema } from "./addressaccount.js";
import {
  PaymentMethodAccount,
  PaymentMethodAccount$zodSchema,
} from "./paymentmethodaccount.js";
import { Profile, Profile$zodSchema } from "./profile.js";

/**
 * The details needed to create a Bolt account.
 */
export type CreateAccountInput = {
  addresses?: Array<AddressAccount> | undefined;
  payment_methods?: Array<PaymentMethodAccount> | undefined;
  profile: Profile;
};

export const CreateAccountInput$zodSchema: z.ZodType<
  CreateAccountInput,
  z.ZodTypeDef,
  unknown
> = z.object({
  addresses: z.array(AddressAccount$zodSchema).optional(),
  payment_methods: z.array(PaymentMethodAccount$zodSchema).optional(),
  profile: Profile$zodSchema,
}).describe("The details needed to create a Bolt account.");
