/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TestingAccountDetails,
  TestingAccountDetails$zodSchema,
} from "./testingaccountdetails.js";
import {
  TestingAccountRequest,
  TestingAccountRequest$zodSchema,
} from "./testingaccountrequest.js";

export type CreateTestingShopperAccountRequest = {
  xPublishableKey?: string | undefined;
  testing_account_request?: TestingAccountRequest | undefined;
};

export const CreateTestingShopperAccountRequest$zodSchema: z.ZodType<
  CreateTestingShopperAccountRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  testing_account_request: TestingAccountRequest$zodSchema.optional(),
  xPublishableKey: z.string().describe(
    "The publicly viewable identifier used to identify a merchant division. This key is found in the Developer > API section of the Bolt Merchant Dashboard [RECOMMENDED].",
  ).optional(),
});

export type CreateTestingShopperAccountResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  testing_account_details?: TestingAccountDetails | undefined;
};

export const CreateTestingShopperAccountResponse$zodSchema: z.ZodType<
  CreateTestingShopperAccountResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  testing_account_details: TestingAccountDetails$zodSchema.optional(),
});
