/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ErrorsBoltApiResponse,
  ErrorsBoltApiResponse$zodSchema,
} from "./errorsboltapiresponse.js";
import {
  EventGroupCreateWebhook,
  EventGroupCreateWebhook$zodSchema,
} from "./eventgroupcreatewebhook.js";
import {
  EventsArrayCreateWebhook,
  EventsArrayCreateWebhook$zodSchema,
} from "./eventsarraycreatewebhook.js";

/**
 * Webhook that receives notifications.
 */
export type CreateWebhookRequest =
  | EventGroupCreateWebhook
  | EventsArrayCreateWebhook;

export const CreateWebhookRequest$zodSchema: z.ZodType<
  CreateWebhookRequest,
  z.ZodTypeDef,
  unknown
> = z.union([
  EventGroupCreateWebhook$zodSchema,
  EventsArrayCreateWebhook$zodSchema,
]).describe("Webhook that receives notifications.");

/**
 * Success
 */
export type CreateWebhookResponseBody = { webhook_id: string };

export const CreateWebhookResponseBody$zodSchema: z.ZodType<
  CreateWebhookResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  webhook_id: z.string(),
}).describe("Success");

export type CreateWebhookResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: CreateWebhookResponseBody | undefined;
  errors_bolt_api_response?: ErrorsBoltApiResponse | undefined;
};

export const CreateWebhookResponse$zodSchema: z.ZodType<
  CreateWebhookResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  errors_bolt_api_response: ErrorsBoltApiResponse$zodSchema.optional(),
  object: z.lazy(() => CreateWebhookResponseBody$zodSchema).optional(),
});
