/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Specifies why this particular transaction is voided.
 */
export const CreditCardVoidCause$zodSchema = z.enum([
  "merchant_action",
  "paypal_sync",
  "amazon_pay_sync",
  "irreversible_reject",
  "auth_expire",
  "auth_verification_expired",
  "payment_method_updater",
]).describe("Specifies why this particular transaction is voided.");

export type CreditCardVoidCause = z.infer<typeof CreditCardVoidCause$zodSchema>;
