/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The status of the void request.
 */
export const CreditCardVoidStatus$zodSchema = z.enum([
  "succeeded",
  "declined",
  "error",
]).describe("The status of the void request.");

export type CreditCardVoidStatus = z.infer<
  typeof CreditCardVoidStatus$zodSchema
>;
