/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AddressView, AddressView$zodSchema } from "./addressview.js";
import {
  CardDisplayNetwork,
  CardDisplayNetwork$zodSchema,
} from "./carddisplaynetwork.js";
import { CardNetwork, CardNetwork$zodSchema } from "./cardnetwork.js";
import { CardStatus, CardStatus$zodSchema } from "./cardstatus.js";
import { CardTokenType, CardTokenType$zodSchema } from "./cardtokentype.js";
import { Priority, Priority$zodSchema } from "./priority.js";

/**
 * Contains details about the credit card transaction.
 */
export type CreditCardView = {
  billing_address?: AddressView | undefined;
  bin?: string | undefined;
  display_network?: CardDisplayNetwork | undefined;
  expiration?: number | undefined;
  icon_asset_path?: string | undefined;
  id?: string | undefined;
  last4?: string | undefined;
  network?: CardNetwork | undefined;
  priority?: Priority | undefined;
  status?: CardStatus | undefined;
  token?: string | undefined;
  token_type?: CardTokenType | undefined;
};

export const CreditCardView$zodSchema: z.ZodType<
  CreditCardView,
  z.ZodTypeDef,
  unknown
> = z.object({
  billing_address: AddressView$zodSchema.optional(),
  bin: z.string().optional(),
  display_network: CardDisplayNetwork$zodSchema.optional(),
  expiration: z.number().int().optional(),
  icon_asset_path: z.string().optional(),
  id: z.string().optional(),
  last4: z.string().optional(),
  network: CardNetwork$zodSchema.optional(),
  priority: Priority$zodSchema.optional(),
  status: CardStatus$zodSchema.optional(),
  token: z.string().optional(),
  token_type: CardTokenType$zodSchema.optional(),
}).describe("Contains details about the credit card transaction.");
