/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AmountView, AmountView$zodSchema } from "./amountview.js";
import { CaptureStatus, CaptureStatus$zodSchema } from "./capturestatus.js";
import {
  TransactionSplitsView,
  TransactionSplitsView$zodSchema,
} from "./transactionsplitsview.js";

export type CreditCardCaptureView = {
  amount?: AmountView | undefined;
  id?: string | undefined;
  merchant_event_id?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  splits?: TransactionSplitsView | undefined;
  status?: CaptureStatus | undefined;
};

export const CreditCardCaptureView$zodSchema: z.ZodType<
  CreditCardCaptureView,
  z.ZodTypeDef,
  unknown
> = z.object({
  amount: AmountView$zodSchema.optional(),
  id: z.string().optional(),
  merchant_event_id: z.string().optional(),
  metadata: z.record(z.string()).optional(),
  splits: TransactionSplitsView$zodSchema.optional(),
  status: CaptureStatus$zodSchema.optional(),
});
