/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Credit = { status?: string | undefined };

export const Credit$zodSchema: z.ZodType<Credit, z.ZodTypeDef, unknown> = z
  .object({
    status: z.string().optional(),
  });
