/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The status of the authorization request.
 *
 * @remarks
 *   * `1` - succeeded
 *   * `2` - declined
 *   * `3` - error
 */
export const CreditCardAuthorizationStatus$zodSchema = z.enum([
  "succeeded",
  "declined",
  "error",
]).describe(
  "The status of the authorization request.\n"
    + "  * `1` - succeeded\n"
    + "  * `2` - declined\n"
    + "  * `3` - error\n"
    + "",
);

export type CreditCardAuthorizationStatus = z.infer<
  typeof CreditCardAuthorizationStatus$zodSchema
>;
