/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Emails, Emails$zodSchema } from "./emails.js";
import {
  PhonesWithCountryCode,
  PhonesWithCountryCode$zodSchema,
} from "./phoneswithcountrycode.js";

/**
 * The credit card user.
 */
export type CreditCardUser = {
  emails?: Array<Emails> | undefined;
  first_name?: string | undefined;
  id?: string | undefined;
  last_name?: string | undefined;
  phones?: Array<PhonesWithCountryCode> | undefined;
};

export const CreditCardUser$zodSchema: z.ZodType<
  CreditCardUser,
  z.ZodTypeDef,
  unknown
> = z.object({
  emails: z.array(Emails$zodSchema).optional(),
  first_name: z.string().optional(),
  id: z.string().optional(),
  last_name: z.string().optional(),
  phones: z.array(PhonesWithCountryCode$zodSchema).optional(),
}).describe("The credit card user.");
