/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The reason code explaining the authorization status.
 *
 * @remarks
 *   * `1` - none
 *   * `2` - invalid_amount
 *   * `3` - invalid_cvv
 *   * `4` - invalid_cc_number
 *   * `5` - expired
 *   * `6` - risk
 *   * `7` - lost_stolen
 *   * `8` - call_issuer
 *   * `9` - invalid_merchant_for_card
 *   * `10` - unsupported_payment_method
 */
export const CreditCardAuthorizationReason$zodSchema = z.enum([
  "none",
  "invalid_amount",
  "invalid_cvv",
  "invalid_cc_number",
  "expired",
  "risk",
  "lost_stolen",
  "call_issuer",
  "invalid_merchant_for_card",
  "unsupported_payment_method",
  "processor_server_error",
]).describe(
  "The reason code explaining the authorization status.\n"
    + "  * `1` - none\n"
    + "  * `2` - invalid_amount\n"
    + "  * `3` - invalid_cvv\n"
    + "  * `4` - invalid_cc_number\n"
    + "  * `5` - expired\n"
    + "  * `6` - risk\n"
    + "  * `7` - lost_stolen\n"
    + "  * `8` - call_issuer\n"
    + "  * `9` - invalid_merchant_for_card\n"
    + "  * `10` - unsupported_payment_method\n"
    + "",
);

export type CreditCardAuthorizationReason = z.infer<
  typeof CreditCardAuthorizationReason$zodSchema
>;
