/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Address, Address$zodSchema } from "./address.js";

/**
 * Used to indicate the card's priority. '1' indicates primary, while '2' indicates a secondary card.
 */
export const CreditCardPriority$zodSchema = z.union([
  z.literal(1),
  z.literal(2),
]).describe(
  "Used to indicate the card's priority. '1' indicates primary, while '2' indicates a secondary card.",
);

export type CreditCardPriority = z.infer<typeof CreditCardPriority$zodSchema>;

/**
 * Used to define which payment processor generated the token for this credit card; for those using Bolt's tokenizer, the value must be `bolt`.
 */
export const CreditCardTokenType$zodSchema = z.enum([
  "bolt",
]).describe(
  "Used to define which payment processor generated the token for this credit card; for those using Bolt's tokenizer, the value must be `bolt`.",
);

export type CreditCardTokenType = z.infer<typeof CreditCardTokenType$zodSchema>;

/**
 * The credit_card object is used to to pay for guest-checkout transactions or save payment method details to an account. Once saved, you can reference the credit card with the associated `credit_card_id` for future transactions. Add `billing_address` to this if storing a billing address for a returning shopper.
 */
export type CreditCard = {
  billing_address?: Address | undefined;
  bin: string;
  expiration: string;
  last4: string;
  postal_code: string;
  priority?: CreditCardPriority | undefined;
  save?: boolean | undefined;
  token: string;
  token_type: CreditCardTokenType;
};

export const CreditCard$zodSchema: z.ZodType<
  CreditCard,
  z.ZodTypeDef,
  unknown
> = z.object({
  billing_address: Address$zodSchema.optional(),
  bin: z.string(),
  expiration: z.string(),
  last4: z.string(),
  postal_code: z.string(),
  priority: CreditCardPriority$zodSchema.optional(),
  save: z.boolean().optional(),
  token: z.string(),
  token_type: CreditCardTokenType$zodSchema,
}).describe(
  "The credit_card object is used to to pay for guest-checkout transactions or save payment method details to an account. Once saved, you can reference the credit card with the associated `credit_card_id` for future transactions. Add `billing_address` to this if storing a billing address for a returning shopper.",
);
