/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CreditCardVoidCause,
  CreditCardVoidCause$zodSchema,
} from "./creditcardvoidcause.js";
import {
  CreditCardVoidStatus,
  CreditCardVoidStatus$zodSchema,
} from "./creditcardvoidstatus.js";

export type CreditCardVoidView = {
  cause?: CreditCardVoidCause | undefined;
  merchant_event_id?: string | undefined;
  status?: CreditCardVoidStatus | undefined;
  void?: string | undefined;
};

export const CreditCardVoidView$zodSchema: z.ZodType<
  CreditCardVoidView,
  z.ZodTypeDef,
  unknown
> = z.object({
  cause: CreditCardVoidCause$zodSchema.optional(),
  merchant_event_id: z.string().optional(),
  status: CreditCardVoidStatus$zodSchema.optional(),
  void: z.string().optional(),
});
