/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The status of the refund to a card.
 */
export const CreditCardCreditViewStatus$zodSchema = z.enum([
  "succeeded",
  "declined",
  "error",
  "pending",
  "in progress",
]).describe("The status of the refund to a card.");

export type CreditCardCreditViewStatus = z.infer<
  typeof CreditCardCreditViewStatus$zodSchema
>;

export type CreditCardCreditView = {
  status?: CreditCardCreditViewStatus | undefined;
  merchant_event_id?: string | undefined;
};

export const CreditCardCreditView$zodSchema: z.ZodType<
  CreditCardCreditView,
  z.ZodTypeDef,
  unknown
> = z.object({
  merchant_event_id: z.string().optional(),
  status: CreditCardCreditViewStatus$zodSchema.optional(),
});
