/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CreditCardVoid = {
  merchant_event_id?: string | undefined;
  skip_hook_notification?: boolean | undefined;
  transaction_reference: string;
};

export const CreditCardVoid$zodSchema: z.ZodType<
  CreditCardVoid,
  z.ZodTypeDef,
  unknown
> = z.object({
  merchant_event_id: z.string().optional(),
  skip_hook_notification: z.boolean().optional(),
  transaction_reference: z.string(),
});
