/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ResponseT = string | boolean;

export const ResponseT$zodSchema: z.ZodType<ResponseT, z.ZodTypeDef, unknown> =
  z.union([
    z.string(),
    z.boolean(),
  ]);

export type CustomFieldResponseView = {
  response?: string | boolean | undefined;
};

export const CustomFieldResponseView$zodSchema: z.ZodType<
  CustomFieldResponseView,
  z.ZodTypeDef,
  unknown
> = z.object({
  response: z.union([
    z.string(),
    z.boolean(),
  ]).optional(),
});
