/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const CustomFieldViewCheckoutStep$zodSchema = z.enum([
  "SHIPPING_STEP",
  "DELIVERY_STEP",
  "PAYMENT_STEP",
  "ACCOUNT_REGISTRATION_SSO",
]);

export type CustomFieldViewCheckoutStep = z.infer<
  typeof CustomFieldViewCheckoutStep$zodSchema
>;

export const CustomFieldViewContext$zodSchema = z.enum([
  "CHECKOUT",
  "SSO",
]);

export type CustomFieldViewContext = z.infer<
  typeof CustomFieldViewContext$zodSchema
>;

export type CustomFieldView = {
  checkout_step?: CustomFieldViewCheckoutStep | undefined;
  dynamic?: boolean | undefined;
  context?: CustomFieldViewContext | undefined;
  external_id?: string | undefined;
  field_setup?: string | undefined;
  label?: string | undefined;
  position?: number | undefined;
  public_id?: string | undefined;
  required?: boolean | undefined;
  subscribeToNewsletter?: boolean | undefined;
};

export const CustomFieldView$zodSchema: z.ZodType<
  CustomFieldView,
  z.ZodTypeDef,
  unknown
> = z.object({
  checkout_step: CustomFieldViewCheckoutStep$zodSchema.optional(),
  context: CustomFieldViewContext$zodSchema.optional(),
  dynamic: z.boolean().optional(),
  external_id: z.string().optional(),
  field_setup: z.string().optional(),
  label: z.string().optional(),
  position: z.number().optional(),
  public_id: z.string().optional(),
  required: z.boolean().optional(),
  subscribeToNewsletter: z.boolean().optional(),
});
