/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CustomFieldResponseView,
  CustomFieldResponseView$zodSchema,
} from "./customfieldresponseview.js";
import {
  CustomFieldView,
  CustomFieldView$zodSchema,
} from "./customfieldview.js";

export type CustomFieldFullResponseView = {
  field?: CustomFieldView | undefined;
  response?: CustomFieldResponseView | undefined;
};

export const CustomFieldFullResponseView$zodSchema: z.ZodType<
  CustomFieldFullResponseView,
  z.ZodTypeDef,
  unknown
> = z.object({
  field: CustomFieldView$zodSchema.optional(),
  response: CustomFieldResponseView$zodSchema.optional(),
});
