/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CustomerListStatus = {
  auto_approved?: boolean | undefined;
  block_listed?: boolean | undefined;
};

export const CustomerListStatus$zodSchema: z.ZodType<
  CustomerListStatus,
  z.ZodTypeDef,
  unknown
> = z.object({
  auto_approved: z.boolean().optional(),
  block_listed: z.boolean().optional(),
});
