/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const CheckoutSetup$zodSchema = z.enum([
  "shipping_step",
  "delivery_step",
  "payment_step",
  "account_registration_sso",
]);

export type CheckoutSetup = z.infer<typeof CheckoutSetup$zodSchema>;

/**
 * The app context of where the custom field is used.
 */
export const CustomFieldsContext$zodSchema = z.enum([
  "CHECKOUT",
  "SSO",
]).describe("The app context of where the custom field is used.");

export type CustomFieldsContext = z.infer<typeof CustomFieldsContext$zodSchema>;

export type CustomFields = {
  checkout_setup?: CheckoutSetup | undefined;
  dynamic?: boolean | undefined;
  context?: CustomFieldsContext | undefined;
  external_id?: string | undefined;
  field_setup?: string | undefined;
  label?: string | undefined;
  position?: number | undefined;
  public_id?: string | undefined;
  required?: boolean | undefined;
  subscribe_to_newsletter?: boolean | undefined;
};

export const CustomFields$zodSchema: z.ZodType<
  CustomFields,
  z.ZodTypeDef,
  unknown
> = z.object({
  checkout_setup: CheckoutSetup$zodSchema.optional(),
  context: CustomFieldsContext$zodSchema.optional(),
  dynamic: z.boolean().optional(),
  external_id: z.string().optional(),
  field_setup: z.string().optional(),
  label: z.string().optional(),
  position: z.number().int().optional(),
  public_id: z.string().optional(),
  required: z.boolean().optional(),
  subscribe_to_newsletter: z.boolean().optional(),
});
