/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ErrorsBoltApiResponse,
  ErrorsBoltApiResponse$zodSchema,
} from "./errorsboltapiresponse.js";

export type DeleteWebhookRequest = { webhook_id: string };

export const DeleteWebhookRequest$zodSchema: z.ZodType<
  DeleteWebhookRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  webhook_id: z.string().describe("Webhook ID"),
});

export type DeleteWebhookResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  errors_bolt_api_response?: ErrorsBoltApiResponse | undefined;
};

export const DeleteWebhookResponse$zodSchema: z.ZodType<
  DeleteWebhookResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  errors_bolt_api_response: ErrorsBoltApiResponse$zodSchema.optional(),
});
