/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteAddressSecurity = { OAuth: string; xAPIKey: string };

export const DeleteAddressSecurity$zodSchema: z.ZodType<
  DeleteAddressSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  OAuth: z.string().describe(
    "Bolt utilizes the OAuth flow that developers can use to attain access to Bolt Account data via APIs.\n"
      + "For all APIs that require authorization, please provide your `access_token` returned from `/v1/oauth/token` via the basic auth bearer header `Authorization: bearer ${TOKEN}`.\n"
      + "[Read more about the OAuth token endpoint.](/api-bolt/#tag/OAuth)\n"
      + "",
  ),
  xAPIKey: z.string().describe(
    "Admins and Developers can obtain their Bolt API key from the Bolt Merchant Dashboard.",
  ),
});

export type DeleteAddressRequest = {
  id: string;
  xPublishableKey?: string | undefined;
};

export const DeleteAddressRequest$zodSchema: z.ZodType<
  DeleteAddressRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().describe(
    "The ID for an address in the shopper's Address Book.",
  ),
  xPublishableKey: z.string().describe(
    "The publicly viewable identifier used to identify a merchant division. This key is found in the Developer > API section of the Bolt Merchant Dashboard [RECOMMENDED].",
  ).optional(),
});

export type DeleteAddressResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
};

export const DeleteAddressResponse$zodSchema: z.ZodType<
  DeleteAddressResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
});
