/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DigitalDelivery = {
  email?: string | undefined;
  phone?: string | undefined;
};

export const DigitalDelivery$zodSchema: z.ZodType<
  DigitalDelivery,
  z.ZodTypeDef,
  unknown
> = z.object({
  email: z.string().optional(),
  phone: z.string().optional(),
});
