/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { PaymentService, PaymentService$zodSchema } from "./paymentservice.js";

export type EligiblePaymentMethod = {
  eligible?: boolean | undefined;
  transaction_processor_type?: PaymentService | undefined;
};

export const EligiblePaymentMethod$zodSchema: z.ZodType<
  EligiblePaymentMethod,
  z.ZodTypeDef,
  unknown
> = z.object({
  eligible: z.boolean().optional(),
  transaction_processor_type: PaymentService$zodSchema.optional(),
});
