/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { EmailPriority, EmailPriority$zodSchema } from "./emailpriority.js";
import { EmailStatus, EmailStatus$zodSchema } from "./emailstatus.js";

/**
 * An object of user email.
 */
export type Emails = {
  address?: string | undefined;
  id?: string | undefined;
  priority?: EmailPriority | undefined;
  status?: EmailStatus | undefined;
};

export const Emails$zodSchema: z.ZodType<Emails, z.ZodTypeDef, unknown> = z
  .object({
    address: z.string().optional(),
    id: z.string().optional(),
    priority: EmailPriority$zodSchema.optional(),
    status: EmailStatus$zodSchema.optional(),
  }).describe("An object of user email.");
