/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Priority, Priority$zodSchema } from "./priority.js";

export type EmailView = {
  address?: string | undefined;
  id?: string | undefined;
  priority?: Priority | undefined;
  status?: string | undefined;
};

export const EmailView$zodSchema: z.ZodType<EmailView, z.ZodTypeDef, unknown> =
  z.object({
    address: z.string().optional(),
    id: z.string().optional(),
    priority: Priority$zodSchema.optional(),
    status: z.string().optional(),
  });
