/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Error object containing custom error information
 */
export type ErrorBoltApi = {
  code?: number | undefined;
  message?: string | undefined;
};

export const ErrorBoltApi$zodSchema: z.ZodType<
  ErrorBoltApi,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: z.number().int().optional(),
  message: z.string().optional(),
}).describe("Error object containing custom error information");
