/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Invalid request to OAuth Token.
 */
export type ErrorsOauthServerResponse = {
  error?: string | undefined;
  error_description?: string | undefined;
};

export const ErrorsOauthServerResponse$zodSchema: z.ZodType<
  ErrorsOauthServerResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string().optional(),
  error_description: z.string().optional(),
}).describe("Invalid request to OAuth Token.");
