/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorBoltApi, ErrorBoltApi$zodSchema } from "./errorboltapi.js";
import { RequestResult, RequestResult$zodSchema } from "./requestresult.js";

export type ErrorsBoltApiResponse = {
  errors?: Array<ErrorBoltApi> | undefined;
  result?: RequestResult | undefined;
};

export const ErrorsBoltApiResponse$zodSchema: z.ZodType<
  ErrorsBoltApiResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  errors: z.array(ErrorBoltApi$zodSchema).optional(),
  result: RequestResult$zodSchema.optional(),
});
