/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  WebhookEventGroup,
  WebhookEventGroup$zodSchema,
} from "./webhookeventgroup.js";

export type EventGroupCreateWebhook = {
  division_id: string;
  url: string;
  event_group?: WebhookEventGroup | null | undefined;
};

export const EventGroupCreateWebhook$zodSchema: z.ZodType<
  EventGroupCreateWebhook,
  z.ZodTypeDef,
  unknown
> = z.object({
  division_id: z.string(),
  event_group: WebhookEventGroup$zodSchema.nullable().optional(),
  url: z.string(),
});
