/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { WebhooksType, WebhooksType$zodSchema } from "./webhookstype.js";

export type EventsArrayCreateWebhook = {
  division_id: string;
  url: string;
  events?: Array<WebhooksType> | undefined;
};

export const EventsArrayCreateWebhook$zodSchema: z.ZodType<
  EventsArrayCreateWebhook,
  z.ZodTypeDef,
  unknown
> = z.object({
  division_id: z.string(),
  events: z.array(WebhooksType$zodSchema).optional(),
  url: z.string(),
});
