/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ICartItemView, ICartItemView$zodSchema } from "./icartitemview.js";
import {
  ICartShipmentView,
  ICartShipmentView$zodSchema,
} from "./icartshipmentview.js";
import {
  InStoreShipment2,
  InStoreShipment2$zodSchema,
} from "./instoreshipment2.js";

export type FulfillmentView = {
  cart_shipment?: ICartShipmentView | undefined;
  fulfillment_type?: string | undefined;
  id?: string | undefined;
  in_store_cart_shipment?: InStoreShipment2 | undefined;
  items?: Array<ICartItemView> | undefined;
};

export const FulfillmentView$zodSchema: z.ZodType<
  FulfillmentView,
  z.ZodTypeDef,
  unknown
> = z.object({
  cart_shipment: ICartShipmentView$zodSchema.optional(),
  fulfillment_type: z.string().optional(),
  id: z.string().optional(),
  in_store_cart_shipment: InStoreShipment2$zodSchema.optional(),
  items: z.array(ICartItemView$zodSchema).optional(),
});
