/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { CartItem, CartItem$zodSchema } from "./cartitem.js";
import { CartShipment, CartShipment$zodSchema } from "./cartshipment.js";
import {
  DigitalDelivery,
  DigitalDelivery$zodSchema,
} from "./digitaldelivery.js";
import {
  InStoreCartShipment,
  InStoreCartShipment$zodSchema,
} from "./instorecartshipment.js";

export const FulfillmentType$zodSchema = z.enum([
  "physical_door_delivery",
  "physical_ship_to_store",
  "physical_in_store_pickup",
  "digital_download",
  "digital_no_delivery",
]);

export type FulfillmentType = z.infer<typeof FulfillmentType$zodSchema>;

/**
 * Defines the shipments associated with the cart items.
 */
export type Fulfillment = {
  cart_items?: Array<CartItem> | undefined;
  cart_shipment?: CartShipment | undefined;
  digital_delivery?: DigitalDelivery | undefined;
  in_store_cart_shipment?: InStoreCartShipment | undefined;
  type?: FulfillmentType | undefined;
};

export const Fulfillment$zodSchema: z.ZodType<
  Fulfillment,
  z.ZodTypeDef,
  unknown
> = z.object({
  cart_items: z.array(CartItem$zodSchema).optional(),
  cart_shipment: CartShipment$zodSchema.optional(),
  digital_delivery: DigitalDelivery$zodSchema.optional(),
  in_store_cart_shipment: InStoreCartShipment$zodSchema.optional(),
  type: FulfillmentType$zodSchema.optional(),
}).describe("Defines the shipments associated with the cart items.");
