/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ErrorsBoltApiResponse,
  ErrorsBoltApiResponse$zodSchema,
} from "./errorsboltapiresponse.js";
import {
  MerchantCallbacksView,
  MerchantCallbacksView$zodSchema,
} from "./merchantcallbacksview.js";

export type GetMerchantCallbacksRequest = { division_id: string };

export const GetMerchantCallbacksRequest$zodSchema: z.ZodType<
  GetMerchantCallbacksRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  division_id: z.string().describe(
    "The unique ID associated to the merchant's Bolt Account division; Merchants can have different divisions to suit multiple use cases (storefronts, pay-by-link, phone order processing). You can view and switch between these divisions from the Bolt Merchant Dashboard.",
  ),
});

export type GetMerchantCallbacksResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  merchant_callbacks_view?: MerchantCallbacksView | undefined;
  errors_bolt_api_response?: ErrorsBoltApiResponse | undefined;
};

export const GetMerchantCallbacksResponse$zodSchema: z.ZodType<
  GetMerchantCallbacksResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  errors_bolt_api_response: ErrorsBoltApiResponse$zodSchema.optional(),
  merchant_callbacks_view: MerchantCallbacksView$zodSchema.optional(),
});
