/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ErrorsBoltApiResponse,
  ErrorsBoltApiResponse$zodSchema,
} from "./errorsboltapiresponse.js";
import {
  MerchantIdentifiersView,
  MerchantIdentifiersView$zodSchema,
} from "./merchantidentifiersview.js";

export type GetMerchantIdentifiersResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  merchant_identifiers_view?: MerchantIdentifiersView | undefined;
  errors_bolt_api_response?: ErrorsBoltApiResponse | undefined;
};

export const GetMerchantIdentifiersResponse$zodSchema: z.ZodType<
  GetMerchantIdentifiersResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  errors_bolt_api_response: ErrorsBoltApiResponse$zodSchema.optional(),
  merchant_identifiers_view: MerchantIdentifiersView$zodSchema.optional(),
});
