/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ErrorsBoltApiResponse,
  ErrorsBoltApiResponse$zodSchema,
} from "./errorsboltapiresponse.js";
import {
  StatementsViewResponse,
  StatementsViewResponse$zodSchema,
} from "./statementsviewresponse.js";

export type GetStatementsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  statements_view?: StatementsViewResponse | undefined;
  errors_bolt_api_response?: ErrorsBoltApiResponse | undefined;
};

export const GetStatementsResponse$zodSchema: z.ZodType<
  GetStatementsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  errors_bolt_api_response: ErrorsBoltApiResponse$zodSchema.optional(),
  statements_view: StatementsViewResponse$zodSchema.optional(),
});
