/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ErrorsBoltApiResponse,
  ErrorsBoltApiResponse$zodSchema,
} from "./errorsboltapiresponse.js";
import {
  TransactionDetails,
  TransactionDetails$zodSchema,
} from "./transactiondetails.js";

export type GetTransactionDetailsRequest = { REFERENCE: string };

export const GetTransactionDetailsRequest$zodSchema: z.ZodType<
  GetTransactionDetailsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  REFERENCE: z.string().describe(
    "This is the Bolt transaction reference. (ex. N7Y3-NFKC-VFRF)",
  ),
});

export type GetTransactionDetailsResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  transaction_details?: TransactionDetails | undefined;
  errors_bolt_api_response?: ErrorsBoltApiResponse | undefined;
};

export const GetTransactionDetailsResponse$zodSchema: z.ZodType<
  GetTransactionDetailsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  errors_bolt_api_response: ErrorsBoltApiResponse$zodSchema.optional(),
  transaction_details: TransactionDetails$zodSchema.optional(),
});
