/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ErrorsBoltApiResponse,
  ErrorsBoltApiResponse$zodSchema,
} from "./errorsboltapiresponse.js";
import { Webhook, Webhook$zodSchema } from "./webhook.js";

export type GetWebhookRequest = { webhook_id: string };

export const GetWebhookRequest$zodSchema: z.ZodType<
  GetWebhookRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  webhook_id: z.string().describe("Webhook ID"),
});

export type GetWebhookResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  webhook?: Webhook | undefined;
  errors_bolt_api_response?: ErrorsBoltApiResponse | undefined;
};

export const GetWebhookResponse$zodSchema: z.ZodType<
  GetWebhookResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  errors_bolt_api_response: ErrorsBoltApiResponse$zodSchema.optional(),
  webhook: Webhook$zodSchema.optional(),
});
