/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Contains the gift option settings for wrapping and custom messages.
 */
export type GiftOptions = {
  message?: string | undefined;
  wrap?: boolean | undefined;
};

export const GiftOptions$zodSchema: z.ZodType<
  GiftOptions,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string().optional(),
  wrap: z.boolean().optional(),
}).describe(
  "Contains the gift option settings for wrapping and custom messages.",
);
