/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Defines which gift options are hidden.
 */
export type GiftOptionView = {
  hide_gift_message?: boolean | undefined;
  hide_gift_wrap?: boolean | undefined;
};

export const GiftOptionView$zodSchema: z.ZodType<
  GiftOptionView,
  z.ZodTypeDef,
  unknown
> = z.object({
  hide_gift_message: z.boolean().optional(),
  hide_gift_wrap: z.boolean().optional(),
}).describe("Defines which gift options are hidden.");
