/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TransactionView,
  TransactionView$zodSchema,
} from "./transactionview.js";

export type IAuthorizeResultView = {
  did_create_bolt_account?: boolean | undefined;
  order_number?: string | undefined;
  transaction?: TransactionView | undefined;
};

export const IAuthorizeResultView$zodSchema: z.ZodType<
  IAuthorizeResultView,
  z.ZodTypeDef,
  unknown
> = z.object({
  did_create_bolt_account: z.boolean().optional(),
  order_number: z.string().optional(),
  transaction: TransactionView$zodSchema.optional(),
});
