/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AmountView, AmountView$zodSchema } from "./amountview.js";

export type ICartFeeView = {
  reference?: string | undefined;
  name?: string | null | undefined;
  description?: string | null | undefined;
  unit_price?: AmountView | undefined;
  unit_tax_amount?: AmountView | undefined;
  quantity?: number | undefined;
};

export const ICartFeeView$zodSchema: z.ZodType<
  ICartFeeView,
  z.ZodTypeDef,
  unknown
> = z.object({
  description: z.string().nullable().optional(),
  name: z.string().nullable().optional(),
  quantity: z.number().optional(),
  reference: z.string().optional(),
  unit_price: AmountView$zodSchema.optional(),
  unit_tax_amount: AmountView$zodSchema.optional(),
});
