/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AmountView, AmountView$zodSchema } from "./amountview.js";
import {
  IFreeShippingDiscountView,
  IFreeShippingDiscountView$zodSchema,
} from "./ifreeshippingdiscountview.js";

export const ICartDiscountViewDiscountCategory$zodSchema = z.enum([
  "coupon",
  "giftcard",
  "managed_giftcard",
  "store_credit",
  "automatic_promotion",
  "membership_discount",
  "membership_giftcard",
  "subscription_discount",
  "rewards_discount",
  "unknown",
]);

export type ICartDiscountViewDiscountCategory = z.infer<
  typeof ICartDiscountViewDiscountCategory$zodSchema
>;

export type ICartDiscountView = {
  amount?: AmountView | undefined;
  code?: string | undefined;
  description?: string | undefined;
  details_url?: string | undefined;
  discount_category?: ICartDiscountViewDiscountCategory | undefined;
  free_shipping?: IFreeShippingDiscountView | undefined;
  reference?: string | undefined;
};

export const ICartDiscountView$zodSchema: z.ZodType<
  ICartDiscountView,
  z.ZodTypeDef,
  unknown
> = z.object({
  amount: AmountView$zodSchema.optional(),
  code: z.string().optional(),
  description: z.string().optional(),
  details_url: z.string().optional(),
  discount_category: ICartDiscountViewDiscountCategory$zodSchema.optional(),
  free_shipping: IFreeShippingDiscountView$zodSchema.optional(),
  reference: z.string().optional(),
});
