/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AddressView, AddressView$zodSchema } from "./addressview.js";
import { AmountView, AmountView$zodSchema } from "./amountview.js";
import {
  ICartDiscountView,
  ICartDiscountView$zodSchema,
} from "./icartdiscountview.js";
import { ICartFeeView, ICartFeeView$zodSchema } from "./icartfeeview.js";
import { ICartItemView, ICartItemView$zodSchema } from "./icartitemview.js";
import {
  ICartShipmentView,
  ICartShipmentView$zodSchema,
} from "./icartshipmentview.js";
import { ICurrency, ICurrency$zodSchema } from "./icurrency.js";

/**
 * This is the cart object returned in a successful response.
 */
export type ICartView = {
  billing_address?: AddressView | undefined;
  cart_url?: string | undefined;
  currency?: ICurrency | undefined;
  discount_amount?: AmountView | undefined;
  discounts?: Array<ICartDiscountView> | undefined;
  display_id?: string | undefined;
  fee_amount?: AmountView | undefined;
  fees?: Array<ICartFeeView> | undefined;
  items?: Array<ICartItemView> | undefined;
  merchant_order_url?: string | undefined;
  order_description?: string | undefined;
  order_reference?: string | undefined;
  shipments?: Array<ICartShipmentView> | undefined;
  shipping_amount?: AmountView | undefined;
  subtotal_amount?: AmountView | undefined;
  tax_amount?: AmountView | undefined;
  total_amount?: AmountView | undefined;
  transaction_reference?: string | undefined;
};

export const ICartView$zodSchema: z.ZodType<ICartView, z.ZodTypeDef, unknown> =
  z.object({
    billing_address: AddressView$zodSchema.optional(),
    cart_url: z.string().optional(),
    currency: ICurrency$zodSchema.optional(),
    discount_amount: AmountView$zodSchema.optional(),
    discounts: z.array(ICartDiscountView$zodSchema).optional(),
    display_id: z.string().optional(),
    fee_amount: AmountView$zodSchema.optional(),
    fees: z.array(ICartFeeView$zodSchema).optional(),
    items: z.array(ICartItemView$zodSchema).optional(),
    merchant_order_url: z.string().optional(),
    order_description: z.string().optional(),
    order_reference: z.string().optional(),
    shipments: z.array(ICartShipmentView$zodSchema).optional(),
    shipping_amount: AmountView$zodSchema.optional(),
    subtotal_amount: AmountView$zodSchema.optional(),
    tax_amount: AmountView$zodSchema.optional(),
    total_amount: AmountView$zodSchema.optional(),
    transaction_reference: z.string().optional(),
  }).describe("This is the cart object returned in a successful response.");
