/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ICartItemExternalInputs = {
  shopify_line_item_reference?: number | undefined;
  shopify_product_reference?: number | undefined;
  shopify_product_variant_reference?: number | undefined;
};

export const ICartItemExternalInputs$zodSchema: z.ZodType<
  ICartItemExternalInputs,
  z.ZodTypeDef,
  unknown
> = z.object({
  shopify_line_item_reference: z.number().optional(),
  shopify_product_reference: z.number().optional(),
  shopify_product_variant_reference: z.number().optional(),
});
