/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ICurrency = {
  currency?: string | undefined;
  currency_symbol?: string | undefined;
};

export const ICurrency$zodSchema: z.ZodType<ICurrency, z.ZodTypeDef, unknown> =
  z.object({
    currency: z.string().optional(),
    currency_symbol: z.string().optional(),
  });
