/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const ICustomFieldViewCheckoutStep$zodSchema = z.enum([
  "SHIPPING_STEP",
  "DELIVERY_STEP",
  "PAYMENT_STEP",
  "ACCOUNT_REGISTRATION_SSO",
]);

export type ICustomFieldViewCheckoutStep = z.infer<
  typeof ICustomFieldViewCheckoutStep$zodSchema
>;

export const ICustomFieldViewContext$zodSchema = z.enum([
  "CHECKOUT",
  "SSO",
]);

export type ICustomFieldViewContext = z.infer<
  typeof ICustomFieldViewContext$zodSchema
>;

export type ICustomFieldView = {
  checkout_step?: ICustomFieldViewCheckoutStep | undefined;
  dynamic?: boolean | undefined;
  context?: ICustomFieldViewContext | undefined;
  external_id?: string | undefined;
  field_setup?: string | undefined;
  helper_text?: string | undefined;
  label?: string | undefined;
  position?: number | undefined;
  public_id?: string | undefined;
  required?: boolean | undefined;
  subscribeToNewsletter?: boolean | undefined;
};

export const ICustomFieldView$zodSchema: z.ZodType<
  ICustomFieldView,
  z.ZodTypeDef,
  unknown
> = z.object({
  checkout_step: ICustomFieldViewCheckoutStep$zodSchema.optional(),
  context: ICustomFieldViewContext$zodSchema.optional(),
  dynamic: z.boolean().optional(),
  external_id: z.string().optional(),
  field_setup: z.string().optional(),
  helper_text: z.string().optional(),
  label: z.string().optional(),
  position: z.number().optional(),
  public_id: z.string().optional(),
  required: z.boolean().optional(),
  subscribeToNewsletter: z.boolean().optional(),
});
