/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type IDescriptionPart = {
  content?: string | undefined;
  is_html?: boolean | undefined;
};

export const IDescriptionPart$zodSchema: z.ZodType<
  IDescriptionPart,
  z.ZodTypeDef,
  unknown
> = z.object({
  content: z.string().optional(),
  is_html: z.boolean().optional(),
});
