/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type IDescriptionTooltip = {
  html_content?: string | undefined;
  target?: number | undefined;
};

export const IDescriptionTooltip$zodSchema: z.ZodType<
  IDescriptionTooltip,
  z.ZodTypeDef,
  unknown
> = z.object({
  html_content: z.string().optional(),
  target: z.number().optional(),
});
