/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type IFreeShippingDiscountView = {
  is_free_shipping?: boolean | undefined;
  maximum_cost_allowed?: number | undefined;
};

export const IFreeShippingDiscountView$zodSchema: z.ZodType<
  IFreeShippingDiscountView,
  z.ZodTypeDef,
  unknown
> = z.object({
  is_free_shipping: z.boolean().optional(),
  maximum_cost_allowed: z.number().optional(),
});
