/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type IGiftOptionView = {
  hide_gift_message?: boolean | undefined;
  hide_gift_wrap?: boolean | undefined;
};

export const IGiftOptionView$zodSchema: z.ZodType<
  IGiftOptionView,
  z.ZodTypeDef,
  unknown
> = z.object({
  hide_gift_message: z.boolean().optional(),
  hide_gift_wrap: z.boolean().optional(),
});
