/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Amounts, Amounts$zodSchema } from "./amounts.js";
import {
  ConsumerBillingAddress,
  ConsumerBillingAddress$zodSchema,
} from "./consumerbillingaddress.js";
import { GiftOptions, GiftOptions$zodSchema } from "./giftoptions.js";
import {
  PackageDimension,
  PackageDimension$zodSchema,
} from "./packagedimension.js";
import { PackageWeights, PackageWeights$zodSchema } from "./packageweights.js";
import { TotalWeight, TotalWeight$zodSchema } from "./totalweight.js";

/**
 * A cart that is being prepared for shipment
 */
export type InStoreShipment = {
  carrier?: string | undefined;
  cost?: Amounts | undefined;
  default?: boolean | undefined;
  estimated_delivery_date?: string | undefined;
  expedited?: boolean | undefined;
  gift_options?: GiftOptions | undefined;
  id?: string | undefined;
  package_dimension?: PackageDimension | undefined;
  package_type?: string | undefined;
  package_weights?: PackageWeights | undefined;
  reference?: string | undefined;
  service?: string | undefined;
  shipping_address?: ConsumerBillingAddress | undefined;
  shipping_method?: string | undefined;
  signature?: string | undefined;
  tax_amount?: Amounts | undefined;
  total_weight?: TotalWeight | undefined;
};

export const InStoreShipment$zodSchema: z.ZodType<
  InStoreShipment,
  z.ZodTypeDef,
  unknown
> = z.object({
  carrier: z.string().optional(),
  cost: Amounts$zodSchema.optional(),
  default: z.boolean().optional(),
  estimated_delivery_date: z.string().optional(),
  expedited: z.boolean().optional(),
  gift_options: GiftOptions$zodSchema.optional(),
  id: z.string().optional(),
  package_dimension: PackageDimension$zodSchema.optional(),
  package_type: z.string().optional(),
  package_weights: PackageWeights$zodSchema.optional(),
  reference: z.string().optional(),
  service: z.string().optional(),
  shipping_address: ConsumerBillingAddress$zodSchema.optional(),
  shipping_method: z.string().optional(),
  signature: z.string().optional(),
  tax_amount: Amounts$zodSchema.optional(),
  total_weight: TotalWeight$zodSchema.optional(),
}).describe("A cart that is being prepared for shipment");
