/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Address, Address$zodSchema } from "./address.js";
import { CartShipment, CartShipment$zodSchema } from "./cartshipment.js";

export const InStoreCartShipmentDistanceUnit$zodSchema = z.enum([
  "km",
  "mile",
]);

export type InStoreCartShipmentDistanceUnit = z.infer<
  typeof InStoreCartShipmentDistanceUnit$zodSchema
>;

export type InStoreCartShipment = {
  cart_shipment?: CartShipment | undefined;
  description?: string | undefined;
  distance?: number | undefined;
  distance_unit?: InStoreCartShipmentDistanceUnit | undefined;
  in_store_pickup_address?: Address | undefined;
  pickup_window_close?: number | undefined;
  pickup_window_open?: number | undefined;
  store_name?: string | undefined;
};

export const InStoreCartShipment$zodSchema: z.ZodType<
  InStoreCartShipment,
  z.ZodTypeDef,
  unknown
> = z.object({
  cart_shipment: CartShipment$zodSchema.optional(),
  description: z.string().optional(),
  distance: z.number().optional(),
  distance_unit: InStoreCartShipmentDistanceUnit$zodSchema.optional(),
  in_store_pickup_address: Address$zodSchema.optional(),
  pickup_window_close: z.number().int().optional(),
  pickup_window_open: z.number().int().optional(),
  store_name: z.string().optional(),
});
