/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AddressView, AddressView$zodSchema } from "./addressview.js";
import {
  InStoreShipment,
  InStoreShipment$zodSchema,
} from "./instoreshipment.js";

export const InStoreShipment2DistanceUnit$zodSchema = z.enum([
  "mile",
  "km",
]);

export type InStoreShipment2DistanceUnit = z.infer<
  typeof InStoreShipment2DistanceUnit$zodSchema
>;

/**
 * A cart that is being prepared for shipment
 */
export type InStoreShipment2 = {
  address?: AddressView | undefined;
  distance?: number | undefined;
  distance_unit?: InStoreShipment2DistanceUnit | undefined;
  shipment?: InStoreShipment | undefined;
  store_name?: string | undefined;
};

export const InStoreShipment2$zodSchema: z.ZodType<
  InStoreShipment2,
  z.ZodTypeDef,
  unknown
> = z.object({
  address: AddressView$zodSchema.optional(),
  distance: z.number().optional(),
  distance_unit: InStoreShipment2DistanceUnit$zodSchema.optional(),
  shipment: InStoreShipment$zodSchema.optional(),
  store_name: z.string().optional(),
}).describe("A cart that is being prepared for shipment");
