/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EligiblePaymentMethod,
  EligiblePaymentMethod$zodSchema,
} from "./eligiblepaymentmethod.js";
import {
  ICustomFieldView,
  ICustomFieldView$zodSchema,
} from "./icustomfieldview.js";
import {
  IGiftOptionView,
  IGiftOptionView$zodSchema,
} from "./igiftoptionview.js";

export const HideApm$zodSchema = z.enum([
  "PAYPAL",
  "AFFIRM",
  "AFTERPAY",
  "AMAZONPAY",
  "KLARNA",
  "RADIALPAYPAL",
  "SEZZLE",
  "RADIALKLARNA",
  "CREDOVA",
  "GOOGLEPAY",
]);

export type HideApm = z.infer<typeof HideApm$zodSchema>;

export type IOrderDynamicContent = {
  custom_fields?: Array<ICustomFieldView> | undefined;
  eligible_payment_methods?: Array<EligiblePaymentMethod> | undefined;
  gift_option_view?: IGiftOptionView | undefined;
  hide_apm?: Array<HideApm> | undefined;
  order_notice?: string | undefined;
  payment_notice?: string | undefined;
  shipping_info_notice?: string | undefined;
  shipping_notice?: string | undefined;
};

export const IOrderDynamicContent$zodSchema: z.ZodType<
  IOrderDynamicContent,
  z.ZodTypeDef,
  unknown
> = z.object({
  custom_fields: z.array(ICustomFieldView$zodSchema).optional(),
  eligible_payment_methods: z.array(EligiblePaymentMethod$zodSchema).optional(),
  gift_option_view: IGiftOptionView$zodSchema.optional(),
  hide_apm: z.array(HideApm$zodSchema).optional(),
  order_notice: z.string().optional(),
  payment_notice: z.string().optional(),
  shipping_info_notice: z.string().optional(),
  shipping_notice: z.string().optional(),
});
