/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ICartView, ICartView$zodSchema } from "./icartview.js";
import {
  IOrderDynamicContent,
  IOrderDynamicContent$zodSchema,
} from "./iorderdynamiccontent.js";
import {
  IOrderExternalData,
  IOrderExternalData$zodSchema,
} from "./iorderexternaldata.js";

export type IOrderView = {
  cart?: ICartView | undefined;
  dynamic_content?: IOrderDynamicContent | undefined;
  external_data?: IOrderExternalData | undefined;
  token?: string | undefined;
  user_note?: string | undefined;
};

export const IOrderView$zodSchema: z.ZodType<
  IOrderView,
  z.ZodTypeDef,
  unknown
> = z.object({
  cart: ICartView$zodSchema.optional(),
  dynamic_content: IOrderDynamicContent$zodSchema.optional(),
  external_data: IOrderExternalData$zodSchema.optional(),
  token: z.string().optional(),
  user_note: z.string().optional(),
});
