/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type IOrderExternalData = { steam_id?: string | undefined };

export const IOrderExternalData$zodSchema: z.ZodType<
  IOrderExternalData,
  z.ZodTypeDef,
  unknown
> = z.object({
  steam_id: z.string().optional(),
});
