/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type IOrderMetadata = { encrypted_user_id?: string | undefined };

export const IOrderMetadata$zodSchema: z.ZodType<
  IOrderMetadata,
  z.ZodTypeDef,
  unknown
> = z.object({
  encrypted_user_id: z.string().optional(),
});
