/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ItemProperty = {
  name?: string | undefined;
  value?: string | undefined;
};

export const ItemProperty$zodSchema: z.ZodType<
  ItemProperty,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  value: z.string().optional(),
});
