/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The shipment type selected by the shopper.
 */
export const ItemShipmentType$zodSchema = z.enum([
  "unknown",
  "door delivery",
  "in_store_pickup",
  "ship_to_store",
]).describe("The shipment type selected by the shopper.");

export type ItemShipmentType = z.infer<typeof ItemShipmentType$zodSchema>;
