/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type IWeight = {
  unit?: string | undefined;
  weight?: number | undefined;
};

export const IWeight$zodSchema: z.ZodType<IWeight, z.ZodTypeDef, unknown> = z
  .object({
    unit: z.string().optional(),
    weight: z.number().optional(),
  });
