/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const Action$zodSchema = z.enum([
  "set_password",
  "rotate_password",
]);

export type Action = z.infer<typeof Action$zodSchema>;

export const Method$zodSchema = z.enum([
  "code",
  "code_password",
  "password",
  "rotate_password",
]);

export type Method = z.infer<typeof Method$zodSchema>;

export type LoginView = {
  actions?: Array<Action> | undefined;
  methods?: Array<Method> | undefined;
  sso_authorization_url?: string | undefined;
};

export const LoginView$zodSchema: z.ZodType<LoginView, z.ZodTypeDef, unknown> =
  z.object({
    actions: z.array(Action$zodSchema).optional(),
    methods: z.array(Method$zodSchema).optional(),
    sso_authorization_url: z.string().optional(),
  });
