/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const ManualDisputesStatus$zodSchema = z.enum([
  "pending",
  "approved",
  "denied",
]);

export type ManualDisputesStatus = z.infer<
  typeof ManualDisputesStatus$zodSchema
>;

export type ManualDisputes = {
  amount?: number | undefined;
  currency?: string | undefined;
  delivery_evidence?: string | undefined;
  delivery_link?: string | undefined;
  dispute_evidence?: string | undefined;
  dispute_link?: string | undefined;
  other_evidence?: string | undefined;
  other_link?: string | undefined;
  reason?: string | undefined;
  status?: ManualDisputesStatus | undefined;
};

export const ManualDisputes$zodSchema: z.ZodType<
  ManualDisputes,
  z.ZodTypeDef,
  unknown
> = z.object({
  amount: z.number().int().optional(),
  currency: z.string().optional(),
  delivery_evidence: z.string().optional(),
  delivery_link: z.string().optional(),
  dispute_evidence: z.string().optional(),
  dispute_link: z.string().optional(),
  other_evidence: z.string().optional(),
  other_link: z.string().optional(),
  reason: z.string().optional(),
  status: ManualDisputesStatus$zodSchema.optional(),
});
