/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Configures the marketplace commission fee structure for a seller split, supporting both percentage-based and flat fee models.
 */
export type MarketplaceCommissionFee = {
  bps: number;
  flat_cents: number;
  metadata?: { [k: string]: string } | null | undefined;
};

export const MarketplaceCommissionFee$zodSchema: z.ZodType<
  MarketplaceCommissionFee,
  z.ZodTypeDef,
  unknown
> = z.object({
  bps: z.number(),
  flat_cents: z.number(),
  metadata: z.record(z.string()).nullable().optional(),
}).describe(
  "Configures the marketplace commission fee structure for a seller split, supporting both percentage-based and flat fee models.",
);
