/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type MerchantDivisionLogoView = {
  domain?: string | undefined;
  resource?: string | undefined;
};

export const MerchantDivisionLogoView$zodSchema: z.ZodType<
  MerchantDivisionLogoView,
  z.ZodTypeDef,
  unknown
> = z.object({
  domain: z.string().optional(),
  resource: z.string().optional(),
});
