/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  MerchantCallbackUrlType,
  MerchantCallbackUrlType$zodSchema,
} from "./merchantcallbackurltype.js";

export type MerchantCallbacksInputCallbackUrl = {
  type: MerchantCallbackUrlType;
  url: string;
};

export const MerchantCallbacksInputCallbackUrl$zodSchema: z.ZodType<
  MerchantCallbacksInputCallbackUrl,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: MerchantCallbackUrlType$zodSchema,
  url: z.string(),
});

export type MerchantCallbacksInput = {
  callback_urls: Array<MerchantCallbacksInputCallbackUrl>;
  division_id: string;
};

export const MerchantCallbacksInput$zodSchema: z.ZodType<
  MerchantCallbacksInput,
  z.ZodTypeDef,
  unknown
> = z.object({
  callback_urls: z.array(
    z.lazy(() => MerchantCallbacksInputCallbackUrl$zodSchema),
  ),
  division_id: z.string(),
});
