/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const MerchantOnboardingStatusCode$zodSchema = z.enum([
  "new_merchant",
  "user_created",
  "form_filled",
  "integration_done",
  "legacy",
  "processor_settings_received",
]);

export type MerchantOnboardingStatusCode = z.infer<
  typeof MerchantOnboardingStatusCode$zodSchema
>;
