/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  MerchantCallbackUrlType,
  MerchantCallbackUrlType$zodSchema,
} from "./merchantcallbackurltype.js";

export type MerchantCallbacksViewCallbackUrl = {
  type?: MerchantCallbackUrlType | undefined;
  url?: string | undefined;
};

export const MerchantCallbacksViewCallbackUrl$zodSchema: z.ZodType<
  MerchantCallbacksViewCallbackUrl,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: MerchantCallbackUrlType$zodSchema.optional(),
  url: z.string().optional(),
});

export type MerchantCallbacksView = {
  callback_urls?: Array<MerchantCallbacksViewCallbackUrl> | undefined;
};

export const MerchantCallbacksView$zodSchema: z.ZodType<
  MerchantCallbacksView,
  z.ZodTypeDef,
  unknown
> = z.object({
  callback_urls: z.array(
    z.lazy(() => MerchantCallbacksViewCallbackUrl$zodSchema),
  ).optional(),
});
