/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  MerchantOnboardingStatusCode,
  MerchantOnboardingStatusCode$zodSchema,
} from "./merchantonboardingstatuscode.js";
import { MerchantStatus, MerchantStatus$zodSchema } from "./merchantstatus.js";
import {
  TransactionOperationalProcessor,
  TransactionOperationalProcessor$zodSchema,
} from "./transactionoperationalprocessor.js";
import {
  TransactionProcessor,
  TransactionProcessor$zodSchema,
} from "./transactionprocessor.js";

export type Merchant = {
  created_at: number;
  description: string;
  onboarding_status?: MerchantOnboardingStatusCode | undefined;
  operational_processors: Array<TransactionOperationalProcessor>;
  processor: TransactionProcessor;
  public_id?: string | undefined;
  status?: MerchantStatus | undefined;
  time_zone: string;
};

export const Merchant$zodSchema: z.ZodType<Merchant, z.ZodTypeDef, unknown> = z
  .object({
    created_at: z.number().int(),
    description: z.string(),
    onboarding_status: MerchantOnboardingStatusCode$zodSchema.optional(),
    operational_processors: z.array(TransactionOperationalProcessor$zodSchema),
    processor: TransactionProcessor$zodSchema,
    public_id: z.string().optional(),
    status: MerchantStatus$zodSchema.optional(),
    time_zone: z.string(),
  });
