/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Bolt merchant division callback URL type
 */
export const MerchantCallbackUrlType$zodSchema = z.enum([
  "oauth_redirect",
  "oauth_logout",
  "get_account",
  "create_order",
  "universal_merchant_api",
  "shipping",
  "tax",
  "update_cart",
  "debug",
  "remote_api",
  "product_info",
  "support_page",
  "account_page",
  "mobile_app_domain",
  "validate_additional_account_data",
  "terms_of_service",
  "privacy_policy",
  "base_domain",
  "confirmation_redirect",
]).describe("Bolt merchant division callback URL type");

export type MerchantCallbackUrlType = z.infer<
  typeof MerchantCallbackUrlType$zodSchema
>;
