/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  MerchantDivisionsIdentifiersView,
  MerchantDivisionsIdentifiersView$zodSchema,
} from "./merchantdivisionsidentifiersview.js";

export type MerchantIdentifiersView = {
  merchant_divisions?: Array<MerchantDivisionsIdentifiersView> | undefined;
  merchant_id?: string | undefined;
  signing_secret?: string | undefined;
};

export const MerchantIdentifiersView$zodSchema: z.ZodType<
  MerchantIdentifiersView,
  z.ZodTypeDef,
  unknown
> = z.object({
  merchant_divisions: z.array(MerchantDivisionsIdentifiersView$zodSchema)
    .optional(),
  merchant_id: z.string().optional(),
  signing_secret: z.string().optional(),
});
