/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const Decision$zodSchema = z.enum([
  "approve",
  "reject",
]);

export type Decision = z.infer<typeof Decision$zodSchema>;

export type MerchantCreditCardReview = {
  decision: Decision;
  transaction_reference: string;
};

export const MerchantCreditCardReview$zodSchema: z.ZodType<
  MerchantCreditCardReview,
  z.ZodTypeDef,
  unknown
> = z.object({
  decision: Decision$zodSchema,
  transaction_reference: z.string(),
});
