/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { MerchantLogo, MerchantLogo$zodSchema } from "./merchantlogo.js";
import {
  MerchantPlatform,
  MerchantPlatform$zodSchema,
} from "./merchantplatform.js";
import { WebhooksType, WebhooksType$zodSchema } from "./webhookstype.js";

export type MerchantDivision = {
  account_page_url?: string | undefined;
  api_base_domain_url?: string | undefined;
  create_order_url?: string | undefined;
  debug_url?: string | undefined;
  description: string;
  get_account_url?: string | undefined;
  shopper_custom_fields_updated_url?: string | undefined;
  hook_type?: WebhooksType | undefined;
  hook_url?: string | undefined;
  id?: string | undefined;
  is_universal_merchant_api: boolean;
  is_webhooks_v2: boolean;
  logo?: MerchantLogo | undefined;
  merchant_id: string;
  oauth_logout_url?: string | undefined;
  oauth_redirect_url?: string | undefined;
  platform?: MerchantPlatform | undefined;
  plugin_config_url?: string | undefined;
  privacy_policy_url?: string | undefined;
  product_info_url?: string | undefined;
  public_id?: string | undefined;
  shipping_and_tax_url?: string | undefined;
  shipping_url: string;
  tax_url: string;
  terms_of_service_url?: string | undefined;
  universal_merchant_api_url?: string | undefined;
  update_cart_url?: string | undefined;
  validate_additional_account_data_url?: string | undefined;
};

export const MerchantDivision$zodSchema: z.ZodType<
  MerchantDivision,
  z.ZodTypeDef,
  unknown
> = z.object({
  account_page_url: z.string().optional(),
  api_base_domain_url: z.string().optional(),
  create_order_url: z.string().optional(),
  debug_url: z.string().optional(),
  description: z.string(),
  get_account_url: z.string().optional(),
  hook_type: WebhooksType$zodSchema.optional(),
  hook_url: z.string().optional(),
  id: z.string().optional(),
  is_universal_merchant_api: z.boolean(),
  is_webhooks_v2: z.boolean(),
  logo: MerchantLogo$zodSchema.optional(),
  merchant_id: z.string(),
  oauth_logout_url: z.string().optional(),
  oauth_redirect_url: z.string().optional(),
  platform: MerchantPlatform$zodSchema.optional(),
  plugin_config_url: z.string().optional(),
  privacy_policy_url: z.string().optional(),
  product_info_url: z.string().optional(),
  public_id: z.string().optional(),
  shipping_and_tax_url: z.string().optional(),
  shipping_url: z.string(),
  shopper_custom_fields_updated_url: z.string().optional(),
  tax_url: z.string(),
  terms_of_service_url: z.string().optional(),
  universal_merchant_api_url: z.string().optional(),
  update_cart_url: z.string().optional(),
  validate_additional_account_data_url: z.string().optional(),
});
