/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type MerchantDivisionsIdentifiersView = {
  division_id?: string | undefined;
  publishable_key?: string | undefined;
};

export const MerchantDivisionsIdentifiersView$zodSchema: z.ZodType<
  MerchantDivisionsIdentifiersView,
  z.ZodTypeDef,
  unknown
> = z.object({
  division_id: z.string().optional(),
  publishable_key: z.string().optional(),
});
