/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The merchant's status:
 *
 * @remarks
 *   * `1` - Active
 *   * `2` - Inactive
 *   * `3` - Offboarding
 */
export const MerchantStatus$zodSchema = z.union([
  z.literal(1),
  z.literal(2),
  z.literal(3),
]).describe(
  "The merchant's status:\n"
    + "  * `1` - Active\n"
    + "  * `2` - Inactive\n"
    + "  * `3` - Offboarding\n"
    + "",
);

export type MerchantStatus = z.infer<typeof MerchantStatus$zodSchema>;
