/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The type of platform being used for this merchant division.
 */
export const MerchantPlatform$zodSchema = z.enum([
  "none",
  "big_commerce",
  "shopify",
  "magento",
  "magento2",
  "woo_commerce",
  "drupal",
  "volusion",
  "prestashop",
  "netsuite",
  "miva",
  "commerce_cloud",
]).describe("The type of platform being used for this merchant division.");

export type MerchantPlatform = z.infer<typeof MerchantPlatform$zodSchema>;
