/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type MetadataComponent = {
  key1?: string | undefined;
  key2?: string | undefined;
};

export const MetadataComponent$zodSchema: z.ZodType<
  MetadataComponent,
  z.ZodTypeDef,
  unknown
> = z.object({
  key1: z.string().optional(),
  key2: z.string().optional(),
});
