/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { TrackingDetail, TrackingDetail$zodSchema } from "./trackingdetail.js";

/**
 * The shipment status of a simulated order.
 */
export const MockTrackingInputStatus$zodSchema = z.enum([
  "in_transit",
  "cancelled",
  "failure",
  "delivered",
]).describe("The shipment status of a simulated order.");

export type MockTrackingInputStatus = z.infer<
  typeof MockTrackingInputStatus$zodSchema
>;

export type MockTrackingInput = {
  delivery_estimate: string;
  status: MockTrackingInputStatus;
  tracking_detail: Array<TrackingDetail>;
  tracking_number: string;
};

export const MockTrackingInput$zodSchema: z.ZodType<
  MockTrackingInput,
  z.ZodTypeDef,
  unknown
> = z.object({
  delivery_estimate: z.string(),
  status: MockTrackingInputStatus$zodSchema,
  tracking_detail: z.array(TrackingDetail$zodSchema),
  tracking_number: z.string(),
});
