/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type OAuthTokenResponse = {
  access_token?: string | undefined;
  expires_in?: number | undefined;
  id_token?: string | undefined;
  refresh_token?: string | undefined;
  refresh_token_scope?: string | undefined;
  scope?: string | undefined;
  token_type?: string | undefined;
};

export const OAuthTokenResponse$zodSchema: z.ZodType<
  OAuthTokenResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  access_token: z.string().optional(),
  expires_in: z.number().int().optional(),
  id_token: z.string().optional(),
  refresh_token: z.string().optional(),
  refresh_token_scope: z.string().optional(),
  scope: z.string().optional(),
  token_type: z.string().optional(),
});
