/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ErrorsOauthServerResponse,
  ErrorsOauthServerResponse$zodSchema,
} from "./errorsoauthserverresponse.js";
import {
  OAuthTokenInput,
  OAuthTokenInput$zodSchema,
} from "./oauthtokeninput.js";
import {
  OAuthTokenInputRefresh,
  OAuthTokenInputRefresh$zodSchema,
} from "./oauthtokeninputrefresh.js";
import {
  OAuthTokenResponse,
  OAuthTokenResponse$zodSchema,
} from "./oauthtokenresponse.js";

export type OAuthTokenRequestBody = OAuthTokenInput | OAuthTokenInputRefresh;

export const OAuthTokenRequestBody$zodSchema: z.ZodType<
  OAuthTokenRequestBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  OAuthTokenInput$zodSchema,
  OAuthTokenInputRefresh$zodSchema,
]);

export type OAuthTokenRequest = {
  xPublishableKey?: string | undefined;
  RequestBody?: OAuthTokenInput | OAuthTokenInputRefresh | undefined;
};

export const OAuthTokenRequest$zodSchema: z.ZodType<
  OAuthTokenRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  RequestBody: z.union([
    OAuthTokenInput$zodSchema,
    OAuthTokenInputRefresh$zodSchema,
  ]).optional(),
  xPublishableKey: z.string().describe(
    "The publicly viewable identifier used to identify a merchant division. This key is found in the Developer > API section of the Bolt Merchant Dashboard [RECOMMENDED].",
  ).optional(),
});

export type OAuthTokenResponseResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  o_auth_token_response?: OAuthTokenResponse | undefined;
  errors_oauth_server_response?: ErrorsOauthServerResponse | undefined;
};

export const OAuthTokenResponseResponse$zodSchema: z.ZodType<
  OAuthTokenResponseResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  errors_oauth_server_response: ErrorsOauthServerResponse$zodSchema.optional(),
  o_auth_token_response: OAuthTokenResponse$zodSchema.optional(),
});
