/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type OrderExternalDataView = { shopify?: string | undefined };

export const OrderExternalDataView$zodSchema: z.ZodType<
  OrderExternalDataView,
  z.ZodTypeDef,
  unknown
> = z.object({
  shopify: z.string().optional(),
});
