/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Order Tracking Successful
 */
export type OrderTrackResponse = {};

export const OrderTrackResponse$zodSchema: z.ZodType<
  OrderTrackResponse,
  z.ZodTypeDef,
  unknown
> = z.object({}).describe("Order Tracking Successful");
