/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type OrderDecisionDetailsView = {
  decision_factors?: Array<string> | undefined;
  score?: number | undefined;
};

export const OrderDecisionDetailsView$zodSchema: z.ZodType<
  OrderDecisionDetailsView,
  z.ZodTypeDef,
  unknown
> = z.object({
  decision_factors: z.array(z.string()).optional(),
  score: z.number().optional(),
});
