/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { CartView, CartView$zodSchema } from "./cartview.js";
import {
  IOrderDynamicContent,
  IOrderDynamicContent$zodSchema,
} from "./iorderdynamiccontent.js";
import {
  OrderExternalDataView,
  OrderExternalDataView$zodSchema,
} from "./orderexternaldataview.js";

export type OrderView = {
  cart?: CartView | undefined;
  dynamic_content?: IOrderDynamicContent | undefined;
  external_data?: OrderExternalDataView | undefined;
  platform_user_id?: string | undefined;
  requires_action?: string | undefined;
  token?: string | undefined;
  user_note?: string | undefined;
};

export const OrderView$zodSchema: z.ZodType<OrderView, z.ZodTypeDef, unknown> =
  z.object({
    cart: CartView$zodSchema.optional(),
    dynamic_content: IOrderDynamicContent$zodSchema.optional(),
    external_data: OrderExternalDataView$zodSchema.optional(),
    platform_user_id: z.string().optional(),
    requires_action: z.string().optional(),
    token: z.string().optional(),
    user_note: z.string().optional(),
  });
