/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  RiskDecisionFactorYml,
  RiskDecisionFactorYml$zodSchema,
} from "./riskdecisionfactoryml.js";

/**
 * Decision and score for an order.
 */
export type OrderDecision = {
  decision_factors?: Array<RiskDecisionFactorYml> | undefined;
  score?: number | undefined;
};

export const OrderDecision$zodSchema: z.ZodType<
  OrderDecision,
  z.ZodTypeDef,
  unknown
> = z.object({
  decision_factors: z.array(RiskDecisionFactorYml$zodSchema).optional(),
  score: z.number().int().optional(),
}).describe("Decision and score for an order.");
