/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Item, Item$zodSchema } from "./item.js";

/**
 * Send order tracking details.
 */
export type OrderTrackRequestBody = {
  carrier: string;
  is_non_bolt_order?: boolean | undefined;
  items: Array<Item>;
  tracking_number: string;
  transaction_reference: string;
};

export const OrderTrackRequestBody$zodSchema: z.ZodType<
  OrderTrackRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  carrier: z.string(),
  is_non_bolt_order: z.boolean().optional(),
  items: z.array(Item$zodSchema),
  tracking_number: z.string(),
  transaction_reference: z.string(),
}).describe("Send order tracking details.");
