/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type PackageWeights = {
  unit?: string | undefined;
  weight?: number | undefined;
};

export const PackageWeights$zodSchema: z.ZodType<
  PackageWeights,
  z.ZodTypeDef,
  unknown
> = z.object({
  unit: z.string().optional(),
  weight: z.number().int().optional(),
});
