/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Contains the package's width, eight, depth, and unit details.
 */
export type PackageDimension = {
  depth?: number | undefined;
  height?: number | undefined;
  unit?: string | undefined;
  width?: number | undefined;
};

export const PackageDimension$zodSchema: z.ZodType<
  PackageDimension,
  z.ZodTypeDef,
  unknown
> = z.object({
  depth: z.number().int().optional(),
  height: z.number().int().optional(),
  unit: z.string().optional(),
  width: z.number().int().optional(),
}).describe("Contains the package's width, eight, depth, and unit details.");
