/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const PaymentService$zodSchema = z.enum([
  "affirm",
  "afterpay",
  "amazon_pay",
  "credova",
  "klarna",
  "paypal",
  "sezzle",
  "radial_klarna",
  "radial_paypal",
  "adyen_gateway",
  "alliance_data",
  "authorize_net",
  "braintree",
  "cardconnect",
  "checkout_com",
  "cybersource",
  "first_data",
  "nmi",
  "orbital",
  "paypal_payflow",
  "radial",
  "rocketgate",
  "shopify_payments",
  "stripe",
  "magentopayment",
  "adyen_payfac",
  "vantiv",
  "google_pay",
  "bolt",
]);

export type PaymentService = z.infer<typeof PaymentService$zodSchema>;
