/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Address, Address$zodSchema } from "./address.js";
import {
  ShopperMetadata,
  ShopperMetadata$zodSchema,
} from "./shoppermetadata.js";

export const Network$zodSchema = z.enum([
  "visa",
  "mastercard",
  "amex",
  "discover",
  "dinersclub",
  "jcb",
  "unionpay",
  "alliancedata",
  "citiplcc",
  "unknown",
]);

export type Network = z.infer<typeof Network$zodSchema>;

/**
 * Used to indicate the card's priority. '1' indicates primary, while '2' indicates a secondary card.
 *
 * @remarks
 */
export const PaymentMethodAccountPriority$zodSchema = z.union([
  z.literal(1),
  z.literal(2),
]).describe(
  "Used to indicate the card's priority. '1' indicates primary, while '2' indicates a secondary card.\n"
    + "",
);

export type PaymentMethodAccountPriority = z.infer<
  typeof PaymentMethodAccountPriority$zodSchema
>;

/**
 * Used to define which payment processor generated the token for this credit card.  For those using Bolt's tokenizer, the value must be `bolt`.
 *
 * @remarks
 */
export const PaymentMethodAccountTokenType$zodSchema = z.enum([
  "vantiv",
  "applepay",
  "bolt",
  "stripe",
  "plcc",
]).describe(
  "Used to define which payment processor generated the token for this credit card.  For those using Bolt's tokenizer, the value must be `bolt`.\n"
    + "",
);

export type PaymentMethodAccountTokenType = z.infer<
  typeof PaymentMethodAccountTokenType$zodSchema
>;

/**
 * The `credit_card` object is used to to pay for guest checkout transactions or save payment method details to an account. Once saved, you can reference the credit card with the associated `credit_card_id` for future transactions.
 *
 * @remarks
 */
export type PaymentMethodAccount = {
  billing_address: Address;
  billing_address_id?: string | null | undefined;
  bin?: string | undefined;
  cryptogram?: string | undefined;
  eci?: string | undefined;
  expiration: string;
  last4?: string | undefined;
  metadata?: ShopperMetadata | null | undefined;
  network?: Network | undefined;
  number?: string | undefined;
  postal_code?: string | undefined;
  priority?: PaymentMethodAccountPriority | undefined;
  save?: boolean | undefined;
  token: string;
  token_type?: PaymentMethodAccountTokenType | undefined;
  default?: boolean | undefined;
};

export const PaymentMethodAccount$zodSchema: z.ZodType<
  PaymentMethodAccount,
  z.ZodTypeDef,
  unknown
> = z.object({
  billing_address: Address$zodSchema,
  billing_address_id: z.string().nullable().optional(),
  bin: z.string().optional(),
  cryptogram: z.string().optional(),
  default: z.boolean().optional(),
  eci: z.string().optional(),
  expiration: z.string(),
  last4: z.string().optional(),
  metadata: ShopperMetadata$zodSchema.nullable().optional(),
  network: Network$zodSchema.optional(),
  number: z.string().optional(),
  postal_code: z.string().optional(),
  priority: PaymentMethodAccountPriority$zodSchema.optional(),
  save: z.boolean().optional(),
  token: z.string(),
  token_type: PaymentMethodAccountTokenType$zodSchema.optional(),
}).describe(
  "The `credit_card` object is used to to pay for guest checkout transactions or save payment method details to an account. Once saved, you can reference the credit card with the associated `credit_card_id` for future transactions.\n"
    + "",
);
