/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const PhoneViewPriority$zodSchema = z.enum([
  "primary",
  "listed",
]);

export type PhoneViewPriority = z.infer<typeof PhoneViewPriority$zodSchema>;

export type PhoneView = {
  country_code?: string | undefined;
  id?: string | undefined;
  number?: string | undefined;
  priority?: PhoneViewPriority | undefined;
  status?: string | undefined;
};

export const PhoneView$zodSchema: z.ZodType<PhoneView, z.ZodTypeDef, unknown> =
  z.object({
    country_code: z.string().optional(),
    id: z.string().optional(),
    number: z.string().optional(),
    priority: PhoneViewPriority$zodSchema.optional(),
    status: z.string().optional(),
  });
