/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { PhonePriority, PhonePriority$zodSchema } from "./phonepriority.js";
import { PhoneStatus, PhoneStatus$zodSchema } from "./phonestatus.js";

/**
 * A phone number with country code.
 */
export type PhonesWithCountryCode = {
  country_code?: string | undefined;
  id?: string | undefined;
  number?: string | undefined;
  priority?: PhonePriority | undefined;
  status?: PhoneStatus | undefined;
};

export const PhonesWithCountryCode$zodSchema: z.ZodType<
  PhonesWithCountryCode,
  z.ZodTypeDef,
  unknown
> = z.object({
  country_code: z.string().optional(),
  id: z.string().optional(),
  number: z.string().optional(),
  priority: PhonePriority$zodSchema.optional(),
  status: PhoneStatus$zodSchema.optional(),
}).describe("A phone number with country code.");
