/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * This is the priority of the contact method. This field's contents are not displayed in the transaction details view.
 */
export const PhonePriority$zodSchema = z.enum([
  "primary",
  "listed",
]).describe(
  "This is the priority of the contact method. This field's contents are not displayed in the transaction details view.",
);

export type PhonePriority = z.infer<typeof PhonePriority$zodSchema>;
