/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * This is the status of the contact method.
 */
export const PhoneStatus$zodSchema = z.enum([
  "active",
  "pending",
  "inactive",
]).describe("This is the status of the contact method.");

export type PhoneStatus = z.infer<typeof PhoneStatus$zodSchema>;
