/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Describes the card's priority.
 *
 * @remarks
 */
export const Priority$zodSchema = z.enum([
  "primary",
  "listed",
]).describe(
  "Describes the card's priority.\n"
    + "",
);

export type Priority = z.infer<typeof Priority$zodSchema>;
