/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Defines which payment method was used to initiate the transaction.
 */
export const ProcessingInitiator$zodSchema = z.enum([
  "initial_card_on_file",
  "initial_recurring",
  "stored_cardholder_initiated",
  "stored_merchant_initiated",
  "following_recurring",
  "cardholder_initiated",
  "recurring",
]).describe(
  "Defines which payment method was used to initiate the transaction.",
);

export type ProcessingInitiator = z.infer<typeof ProcessingInitiator$zodSchema>;
