/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ShopperMetadata,
  ShopperMetadata$zodSchema,
} from "./shoppermetadata.js";

/**
 * The first name, last name, email address, and phone number of a shopper.
 */
export type Profile = {
  email: string;
  first_name: string;
  last_name: string;
  metadata?: ShopperMetadata | null | undefined;
  phone?: string | undefined;
};

export const Profile$zodSchema: z.ZodType<Profile, z.ZodTypeDef, unknown> = z
  .object({
    email: z.string(),
    first_name: z.string(),
    last_name: z.string(),
    metadata: ShopperMetadata$zodSchema.nullable().optional(),
    phone: z.string().optional(),
  }).describe(
    "The first name, last name, email address, and phone number of a shopper.",
  );
