/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ShopperMetadata,
  ShopperMetadata$zodSchema,
} from "./shoppermetadata.js";

/**
 * The shopper's account profile.
 */
export type ProfileView = {
  email?: string | undefined;
  first_name?: string | undefined;
  last_name?: string | undefined;
  metadata?: ShopperMetadata | null | undefined;
  name?: string | undefined;
  phone?: string | undefined;
};

export const ProfileView$zodSchema: z.ZodType<
  ProfileView,
  z.ZodTypeDef,
  unknown
> = z.object({
  email: z.string().optional(),
  first_name: z.string().optional(),
  last_name: z.string().optional(),
  metadata: ShopperMetadata$zodSchema.nullable().optional(),
  name: z.string().optional(),
  phone: z.string().optional(),
}).describe("The shopper's account profile.");
