/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ErrorsBoltApiResponse,
  ErrorsBoltApiResponse$zodSchema,
} from "./errorsboltapiresponse.js";
import { Webhook, Webhook$zodSchema } from "./webhook.js";

export type QueryWebhooksRequest = { division_id: string };

export const QueryWebhooksRequest$zodSchema: z.ZodType<
  QueryWebhooksRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  division_id: z.string().describe(
    "The unique ID associated to the merchant's Bolt Account division; Merchants can have different divisions to suit multiple use cases (storefronts, pay-by-link, phone order processing). You can view and switch between these divisions from the Bolt Merchant Dashboard.",
  ),
});

/**
 * Success
 */
export type QueryWebhooksResponseBody = {
  webhooks?: Array<Webhook> | undefined;
};

export const QueryWebhooksResponseBody$zodSchema: z.ZodType<
  QueryWebhooksResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  webhooks: z.array(Webhook$zodSchema).optional(),
}).describe("Success");

export type QueryWebhooksResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  object?: QueryWebhooksResponseBody | undefined;
  errors_bolt_api_response?: ErrorsBoltApiResponse | undefined;
};

export const QueryWebhooksResponse$zodSchema: z.ZodType<
  QueryWebhooksResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  errors_bolt_api_response: ErrorsBoltApiResponse$zodSchema.optional(),
  object: z.lazy(() => QueryWebhooksResponseBody$zodSchema).optional(),
});
