/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ErrorsBoltApiResponse,
  ErrorsBoltApiResponse$zodSchema,
} from "./errorsboltapiresponse.js";
import {
  TransactionCredit,
  TransactionCredit$zodSchema,
} from "./transactioncredit.js";
import {
  TransactionView,
  TransactionView$zodSchema,
} from "./transactionview.js";

export type RefundTransactionRequest = {
  idempotencyKey?: string | undefined;
  transaction_credit?: TransactionCredit | undefined;
};

export const RefundTransactionRequest$zodSchema: z.ZodType<
  RefundTransactionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  idempotencyKey: z.string().describe(
    "A key created by merchants that ensures `POST` and `PATCH` requests are only performed once. [Read more about Idempotent Requests here](/developers/references/idempotency/).",
  ).optional(),
  transaction_credit: TransactionCredit$zodSchema.optional(),
});

export type RefundTransactionResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  transaction_view?: TransactionView | undefined;
  errors_bolt_api_response?: ErrorsBoltApiResponse | undefined;
};

export const RefundTransactionResponse$zodSchema: z.ZodType<
  RefundTransactionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  errors_bolt_api_response: ErrorsBoltApiResponse$zodSchema.optional(),
  transaction_view: TransactionView$zodSchema.optional(),
});
