/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export const RequestStatus$zodSchema = z.enum([
  "reviewed",
  "needs_review",
  "unknown",
]);

export type RequestStatus = z.infer<typeof RequestStatus$zodSchema>;
