/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Custom-defined Bolt result object.
 */
export type RequestResult = { success?: boolean | undefined };

export const RequestResult$zodSchema: z.ZodType<
  RequestResult,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean().optional(),
}).describe("Custom-defined Bolt result object.");
