/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ReviewTicketView = {
  id?: string | undefined;
  request_deadline?: number | undefined;
  status?: string | undefined;
};

export const ReviewTicketView$zodSchema: z.ZodType<
  ReviewTicketView,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  request_deadline: z.number().optional(),
  status: z.string().optional(),
});
