/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { RequestStatus, RequestStatus$zodSchema } from "./requeststatus.js";

/**
 * Internal use only.
 */
export type ReviewTicket = {
  id?: string | undefined;
  request_deadline?: number | undefined;
  status?: RequestStatus | undefined;
};

export const ReviewTicket$zodSchema: z.ZodType<
  ReviewTicket,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  request_deadline: z.number().int().optional(),
  status: RequestStatus$zodSchema.optional(),
}).describe("Internal use only.");
