/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * One of the main contributing factors to the fraud decision and score.
 */
export const RiskDecisionFactorYml$zodSchema = z.enum([
  "address_details",
  "auth_decline_stolen_card",
  "card_information",
  "cart_details",
  "checkout_behavior",
  "device_specifications",
  "email_details",
  "fraudulent_chargeback",
  "ip_details",
  "phone_details",
  "shipping_details",
  "too_many_attempts",
  "user_history",
]).describe(
  "One of the main contributing factors to the fraud decision and score.",
);

export type RiskDecisionFactorYml = z.infer<
  typeof RiskDecisionFactorYml$zodSchema
>;
