/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  RiskModelResulContributionView,
  RiskModelResulContributionView$zodSchema,
} from "./riskmodelresulcontributionview.js";

export type RiskModelResultView = {
  contribution?: Array<RiskModelResulContributionView> | undefined;
};

export const RiskModelResultView$zodSchema: z.ZodType<
  RiskModelResultView,
  z.ZodTypeDef,
  unknown
> = z.object({
  contribution: z.array(RiskModelResulContributionView$zodSchema).optional(),
});
