/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type RiskModelResulContributionView = {
  category?: string | undefined;
  weight?: string | undefined;
};

export const RiskModelResulContributionView$zodSchema: z.ZodType<
  RiskModelResulContributionView,
  z.ZodTypeDef,
  unknown
> = z.object({
  category: z.string().optional(),
  weight: z.string().optional(),
});
