/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Describes the current Risk Review status. A transaction could be unreviewed, reviewed, or pending manual review by the Bolt team.
 */
export const RiskReviewStatus$zodSchema = z.enum([
  "unknown",
  "needs_review",
  "reviewed",
]).describe(
  "Describes the current Risk Review status. A transaction could be unreviewed, reviewed, or pending manual review by the Bolt team.",
);

export type RiskReviewStatus = z.infer<typeof RiskReviewStatus$zodSchema>;
