/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AddressView, AddressView$zodSchema } from "./addressview.js";
import { CardNetwork, CardNetwork$zodSchema } from "./cardnetwork.js";
import {
  ShopperMetadata,
  ShopperMetadata$zodSchema,
} from "./shoppermetadata.js";

/**
 * The payment method type. If empty, the property defaults to `card`.
 */
export const SavedCreditCardViewType$zodSchema = z.enum([
  "card",
  "paypal",
]).describe(
  "The payment method type. If empty, the property defaults to `card`.",
);

export type SavedCreditCardViewType = z.infer<
  typeof SavedCreditCardViewType$zodSchema
>;

/**
 * Saved Credit Card Detail
 */
export type SavedCreditCardView = {
  billing_address?: AddressView | undefined;
  id?: string | undefined;
  last4?: string | undefined;
  exp_month?: number | undefined;
  exp_year?: number | undefined;
  network?: CardNetwork | undefined;
  default?: boolean | undefined;
  type?: SavedCreditCardViewType | undefined;
  description?: string | undefined;
  metadata?: ShopperMetadata | null | undefined;
};

export const SavedCreditCardView$zodSchema: z.ZodType<
  SavedCreditCardView,
  z.ZodTypeDef,
  unknown
> = z.object({
  billing_address: AddressView$zodSchema.optional(),
  default: z.boolean().optional(),
  description: z.string().optional(),
  exp_month: z.number().int().optional(),
  exp_year: z.number().int().optional(),
  id: z.string().optional(),
  last4: z.string().optional(),
  metadata: ShopperMetadata$zodSchema.nullable().optional(),
  network: CardNetwork$zodSchema.optional(),
  type: SavedCreditCardViewType$zodSchema.optional(),
}).describe("Saved Credit Card Detail");
