/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ShopperMetadata,
  ShopperMetadata$zodSchema,
} from "./shoppermetadata.js";

/**
 * Type field indicates this is a saved PayPal to differentiate it from a saved card.
 */
export const SavedPaypalAccountViewType$zodSchema = z.enum([
  "paypal",
]).describe(
  "Type field indicates this is a saved PayPal to differentiate it from a saved card.",
);

export type SavedPaypalAccountViewType = z.infer<
  typeof SavedPaypalAccountViewType$zodSchema
>;

/**
 * Saved PayPal account details.
 */
export type SavedPaypalAccountView = {
  id?: string | undefined;
  type?: SavedPaypalAccountViewType | undefined;
  description?: string | undefined;
  metadata?: ShopperMetadata | null | undefined;
};

export const SavedPaypalAccountView$zodSchema: z.ZodType<
  SavedPaypalAccountView,
  z.ZodTypeDef,
  unknown
> = z.object({
  description: z.string().optional(),
  id: z.string().optional(),
  metadata: ShopperMetadata$zodSchema.nullable().optional(),
  type: SavedPaypalAccountViewType$zodSchema.optional(),
}).describe("Saved PayPal account details.");
