/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Security = {
  xAPIKey?: string | undefined;
  OAuth?: string | undefined;
};

export const Security$zodSchema: z.ZodType<Security, z.ZodTypeDef, unknown> = z
  .object({
    OAuth: z.string().describe(
      "Bolt utilizes the OAuth flow that developers can use to attain access to Bolt Account data via APIs.\n"
        + "For all APIs that require authorization, please provide your `access_token` returned from `/v1/oauth/token` via the basic auth bearer header `Authorization: bearer ${TOKEN}`.\n"
        + "[Read more about the OAuth token endpoint.](/api-bolt/#tag/OAuth)\n"
        + "",
    ).optional(),
    xAPIKey: z.string().describe(
      "Admins and Developers can obtain their Bolt API key from the Bolt Merchant Dashboard.",
    ).optional(),
  });
