/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  MarketplaceCommissionFee,
  MarketplaceCommissionFee$zodSchema,
} from "./marketplacecommissionfee.js";
import {
  SellerSplitAmounts,
  SellerSplitAmounts$zodSchema,
} from "./sellersplitamounts.js";

/**
 * Defines a seller split configuration for marketplace orders, specifying which items and shipments belong to a seller and how amounts should be calculated and distributed.
 */
export type SellerSplit = {
  seller_id: string;
  amounts: SellerSplitAmounts;
  marketplace_commission_fee: MarketplaceCommissionFee;
};

export const SellerSplit$zodSchema: z.ZodType<
  SellerSplit,
  z.ZodTypeDef,
  unknown
> = z.object({
  amounts: SellerSplitAmounts$zodSchema,
  marketplace_commission_fee: MarketplaceCommissionFee$zodSchema,
  seller_id: z.string(),
}).describe(
  "Defines a seller split configuration for marketplace orders, specifying which items and shipments belong to a seller and how amounts should be calculated and distributed.",
);
