/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Defines the financial breakdown for a seller split, including subtotals, discounts, shipping, taxes, and the final gross amount.
 */
export type SellerSplitAmounts = {
  merchant_subtotal: number;
  discount_total: number;
  shipping_total: number;
  tax_total: number;
  gross_total: number;
};

export const SellerSplitAmounts$zodSchema: z.ZodType<
  SellerSplitAmounts,
  z.ZodTypeDef,
  unknown
> = z.object({
  discount_total: z.number(),
  gross_total: z.number(),
  merchant_subtotal: z.number(),
  shipping_total: z.number(),
  tax_total: z.number(),
}).describe(
  "Defines the financial breakdown for a seller split, including subtotals, discounts, shipping, taxes, and the final gross amount.",
);
