/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ErrorsBoltApiResponse,
  ErrorsBoltApiResponse$zodSchema,
} from "./errorsboltapiresponse.js";

export type SetMerchantCallbacksResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  errors_bolt_api_response?: ErrorsBoltApiResponse | undefined;
};

export const SetMerchantCallbacksResponse$zodSchema: z.ZodType<
  SetMerchantCallbacksResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  errors_bolt_api_response: ErrorsBoltApiResponse$zodSchema.optional(),
});
