/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AmountView, AmountView$zodSchema } from "./amountview.js";

/**
 * **Nullable** for Transactions Details.
 *
 * @remarks
 */
export const SplitsViewType$zodSchema = z.enum([
  "net",
  "processing_fee",
  "bolt_fee",
  "adjustment",
  "float",
  "reserve",
]).describe(
  "**Nullable** for Transactions Details.\n"
    + "",
);

export type SplitsViewType = z.infer<typeof SplitsViewType$zodSchema>;

/**
 * A split of fees by type and amount.
 */
export type SplitsView = {
  amount?: AmountView | undefined;
  type?: SplitsViewType | undefined;
};

export const SplitsView$zodSchema: z.ZodType<
  SplitsView,
  z.ZodTypeDef,
  unknown
> = z.object({
  amount: AmountView$zodSchema.optional(),
  type: SplitsViewType$zodSchema.optional(),
}).describe("A split of fees by type and amount.");
