/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Statements Fetch Successful
 */
export type StatementsViewResponse = { url: string };

export const StatementsViewResponse$zodSchema: z.ZodType<
  StatementsViewResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  url: z.string(),
}).describe("Statements Fetch Successful");
