/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * This is the type of the file. Currently, Bolt only supports CSV statements.
 */
export const StatementsFileType$zodSchema = z.enum([
  "csv",
]).describe(
  "This is the type of the file. Currently, Bolt only supports CSV statements.",
);

export type StatementsFileType = z.infer<typeof StatementsFileType$zodSchema>;
