/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  StatementsFileType,
  StatementsFileType$zodSchema,
} from "./statementsfiletype.js";
import { StatementsType, StatementsType$zodSchema } from "./statementstype.js";

/**
 * View Statements
 */
export type StatementsViewRequestBody = {
  date: number;
  file_type: StatementsFileType;
  type: StatementsType;
};

export const StatementsViewRequestBody$zodSchema: z.ZodType<
  StatementsViewRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  date: z.number().int(),
  file_type: StatementsFileType$zodSchema,
  type: StatementsType$zodSchema,
}).describe("View Statements");
