/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AccountIdentifierStatus,
  AccountIdentifierStatus$zodSchema,
} from "./accountidentifierstatus.js";

export type TestingAccountDetails = {
  email?: string | undefined;
  email_state?: AccountIdentifierStatus | undefined;
  phone?: string | undefined;
  phone_state?: AccountIdentifierStatus | undefined;
  otp_code?: string | undefined;
  migrated_merchant_owner_id?: string | undefined;
  will_deactivate_at?: string | undefined;
  oauth_code?: string | undefined;
};

export const TestingAccountDetails$zodSchema: z.ZodType<
  TestingAccountDetails,
  z.ZodTypeDef,
  unknown
> = z.object({
  email: z.string().optional(),
  email_state: AccountIdentifierStatus$zodSchema.optional(),
  migrated_merchant_owner_id: z.string().optional(),
  oauth_code: z.string().optional(),
  otp_code: z.string().optional(),
  phone: z.string().optional(),
  phone_state: AccountIdentifierStatus$zodSchema.optional(),
  will_deactivate_at: z.string().optional(),
});
