/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AccountIdentifierStatus,
  AccountIdentifierStatus$zodSchema,
} from "./accountidentifierstatus.js";

export type TestingAccountRequest = {
  deactivate_in_days?: number | undefined;
  email?: string | undefined;
  email_state?: AccountIdentifierStatus | undefined;
  phone?: string | undefined;
  phone_state?: AccountIdentifierStatus | undefined;
  migrated?: boolean | undefined;
  has_address?: boolean | undefined;
};

export const TestingAccountRequest$zodSchema: z.ZodType<
  TestingAccountRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  deactivate_in_days: z.number().int().optional(),
  email: z.string().optional(),
  email_state: AccountIdentifierStatus$zodSchema.optional(),
  has_address: z.boolean().optional(),
  migrated: z.boolean().optional(),
  phone: z.string().optional(),
  phone_state: AccountIdentifierStatus$zodSchema.optional(),
});
