/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ErrorsBoltApiResponse,
  ErrorsBoltApiResponse$zodSchema,
} from "./errorsboltapiresponse.js";
import {
  OrderTrackResponse,
  OrderTrackResponse$zodSchema,
} from "./ordertrackresponse.js";

export type TrackOrderResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  order_track?: OrderTrackResponse | undefined;
  errors_bolt_api_response?: ErrorsBoltApiResponse | undefined;
};

export const TrackOrderResponse$zodSchema: z.ZodType<
  TrackOrderResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  errors_bolt_api_response: ErrorsBoltApiResponse$zodSchema.optional(),
  order_track: OrderTrackResponse$zodSchema.optional(),
});
