/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The transit status of the order being tracked.
 */
export const TrackingDetailStatus$zodSchema = z.enum([
  "unknown",
  "pre_transit",
  "in_transit",
  "out_for_delivery",
  "delivered",
  "available_for_pickup",
  "return_to_sender",
  "failure",
  "cancelled",
  "error",
]).describe("The transit status of the order being tracked.");

export type TrackingDetailStatus = z.infer<
  typeof TrackingDetailStatus$zodSchema
>;

export type TrackingDetail = {
  city: string;
  country: string;
  datetime: string;
  message: string;
  state: string;
  status: TrackingDetailStatus;
  zip: string;
};

export const TrackingDetail$zodSchema: z.ZodType<
  TrackingDetail,
  z.ZodTypeDef,
  unknown
> = z.object({
  city: z.string(),
  country: z.string(),
  datetime: z.string().datetime({ offset: true }),
  message: z.string(),
  state: z.string(),
  status: TrackingDetailStatus$zodSchema,
  zip: z.string(),
});
