/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The processor used. **Nullable** for Transactions Details.
 */
export const TransactionProcessor$zodSchema = z.enum([
  "adyen_gateway",
  "adyen_payfac",
  "affirm",
  "afterpay",
  "alliance_data",
  "amazon_pay",
  "authorize_net",
  "braintree",
  "checkout_com",
  "cybersource",
  "first_data",
  "klarna",
  "nmi",
  "orbital",
  "paypal",
  "radial",
  "radial_klarna",
  "radial_paypal",
  "rocketgate",
  "sezzle",
  "shopify_payments",
  "stripe",
  "vantiv",
]).describe("The processor used. **Nullable** for Transactions Details.");

export type TransactionProcessor = z.infer<
  typeof TransactionProcessor$zodSchema
>;
