/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The type of transaction.
 */
export const TransactionType$zodSchema = z.enum([
  "cc_payment",
  "cc_credit",
  "funding_transfer",
  "processing_fee_transfer",
  "reserve_transfer",
  "float_transfer",
  "merchant_credit",
  "merchant_debit",
  "funding_withdrawal",
  "processing_fee_withdrawal",
  "zero_amount",
  "bolt_fee_transfer",
  "bolt_fee_withdrawal",
  "bank_account_verification",
  "authorization_verification",
  "paypal_payment",
  "paypal_refund",
  "apm_payment",
  "apm_refund",
  "zero_amount_verification",
]).describe("The type of transaction.");

export type TransactionType = z.infer<typeof TransactionType$zodSchema>;
