/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TransactionProcessor,
  TransactionProcessor$zodSchema,
} from "./transactionprocessor.js";
import {
  TransactionProcessorStatus,
  TransactionProcessorStatus$zodSchema,
} from "./transactionprocessorstatus.js";

export type TransactionOperationalProcessor = {
  processor: TransactionProcessor;
  status: TransactionProcessorStatus;
};

export const TransactionOperationalProcessor$zodSchema: z.ZodType<
  TransactionOperationalProcessor,
  z.ZodTypeDef,
  unknown
> = z.object({
  processor: TransactionProcessor$zodSchema,
  status: TransactionProcessorStatus$zodSchema,
});
