/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  RiskModelResultView,
  RiskModelResultView$zodSchema,
} from "./riskmodelresultview.js";

export type TransactionReviewView = {
  date?: number | undefined;
  decision?: string | undefined;
  risk_model_result?: RiskModelResultView | undefined;
  source?: string | undefined;
};

export const TransactionReviewView$zodSchema: z.ZodType<
  TransactionReviewView,
  z.ZodTypeDef,
  unknown
> = z.object({
  date: z.number().optional(),
  decision: z.string().optional(),
  risk_model_result: RiskModelResultView$zodSchema.optional(),
  source: z.string().optional(),
});
