/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Describes the reason that the transaction is or is not indemnified by Bolt for fraud.
 *
 * @remarks
 */
export const TransactionIndemnificationReason$zodSchema = z.enum([
  "unknown",
  "checkout",
  "virtual_terminal",
  "merchant_back_office",
  "merchant_force_approved",
  "reversibly_rejected",
  "irreversibly_rejected",
  "risk_engine_approved",
  "analyst_approved",
  "auth_verification",
  "paypal",
  "afterpay",
  "direct_payments",
  "whitelist",
  "external_review",
  "affirm",
  "merchant_ip_address",
  "amazon_pay",
  "apple_pay",
  "phone_order",
  "klarna",
  "cardholder_authentication",
  "address_change_rejected",
  "indemnify_direct_payments",
  "indemnify_virtual_terminal",
  "membership_subscription",
  "embedded_guest_checkout",
  "risk_assessment_only",
  "sezzle",
  "credova",
  "subscription",
  "indemnify_apm_transaction",
]).describe(
  "Describes the reason that the transaction is or is not indemnified by Bolt for fraud.\n"
    + "",
);

export type TransactionIndemnificationReason = z.infer<
  typeof TransactionIndemnificationReason$zodSchema
>;
