/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TransactionUpdateInput = {
  display_id?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
};

export const TransactionUpdateInput$zodSchema: z.ZodType<
  TransactionUpdateInput,
  z.ZodTypeDef,
  unknown
> = z.object({
  display_id: z.string().optional(),
  metadata: z.record(z.string()).optional(),
});
