/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AuthRejectionDetails,
  AuthRejectionDetails$zodSchema,
} from "./authrejectiondetails.js";

export type TransactionRejectionDetailsView = {
  auth_rejection_details?: AuthRejectionDetails | undefined;
};

export const TransactionRejectionDetailsView$zodSchema: z.ZodType<
  TransactionRejectionDetailsView,
  z.ZodTypeDef,
  unknown
> = z.object({
  auth_rejection_details: AuthRejectionDetails$zodSchema.optional(),
});
