/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The processor's status. Only `primary` and `active` processor are displayed.
 */
export const TransactionProcessorStatus$zodSchema = z.enum([
  "primary",
  "active",
  "inactive",
]).describe(
  "The processor's status. Only `primary` and `active` processor are displayed.",
);

export type TransactionProcessorStatus = z.infer<
  typeof TransactionProcessorStatus$zodSchema
>;
