/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The transaction's status.
 */
export const TransactionStatus$zodSchema = z.enum([
  "in_progress",
  "completed",
  "cancelled",
  "failed",
  "pending",
  "created",
  "authorized",
  "rejected_reversible",
  "rejected_irreversible",
]).describe("The transaction's status.");

export type TransactionStatus = z.infer<typeof TransactionStatus$zodSchema>;
