/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type TransactionCredit = {
  amount: number;
  currency: string;
  merchant_event_id?: string | undefined;
  skip_hook_notification?: boolean | undefined;
  transaction_reference: string;
};

export const TransactionCredit$zodSchema: z.ZodType<
  TransactionCredit,
  z.ZodTypeDef,
  unknown
> = z.object({
  amount: z.number().int(),
  currency: z.string(),
  merchant_event_id: z.string().optional(),
  skip_hook_notification: z.boolean().optional(),
  transaction_reference: z.string(),
});
