/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AmountView, AmountView$zodSchema } from "./amountview.js";

export const TransactionSplitsViewType$zodSchema = z.enum([
  "net",
  "processing_fee",
  "float",
  "reserve",
  "adjustment",
  "bolt_fee",
]);

export type TransactionSplitsViewType = z.infer<
  typeof TransactionSplitsViewType$zodSchema
>;

export type TransactionSplitsView = {
  amount?: AmountView | undefined;
  type?: TransactionSplitsViewType | undefined;
};

export const TransactionSplitsView$zodSchema: z.ZodType<
  TransactionSplitsView,
  z.ZodTypeDef,
  unknown
> = z.object({
  amount: AmountView$zodSchema.optional(),
  type: TransactionSplitsViewType$zodSchema.optional(),
});
