/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Describes whether the transaction is indemnified by Bolt for fraud.
 *
 * @remarks
 */
export const TransactionIndemnificationDecision$zodSchema = z.enum([
  "unknown",
  "indemnified",
  "not_indemnified",
]).describe(
  "Describes whether the transaction is indemnified by Bolt for fraud.\n"
    + "",
);

export type TransactionIndemnificationDecision = z.infer<
  typeof TransactionIndemnificationDecision$zodSchema
>;
