/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AmountView, AmountView$zodSchema } from "./amountview.js";
import { CaptureView, CaptureView$zodSchema } from "./captureview.js";
import {
  ConsumerSelfView,
  ConsumerSelfView$zodSchema,
} from "./consumerselfview.js";
import {
  CreditCardAuthorizationView,
  CreditCardAuthorizationView$zodSchema,
} from "./creditcardauthorizationview.js";
import {
  CreditCardCaptureView,
  CreditCardCaptureView$zodSchema,
} from "./creditcardcaptureview.js";
import {
  CreditCardCreditView,
  CreditCardCreditView$zodSchema,
} from "./creditcardcreditview.js";
import { CreditCardView, CreditCardView$zodSchema } from "./creditcardview.js";
import {
  CreditCardVoidView,
  CreditCardVoidView$zodSchema,
} from "./creditcardvoidview.js";
import {
  MerchantDivisionSummaryView,
  MerchantDivisionSummaryView$zodSchema,
} from "./merchantdivisionsummaryview.js";
import {
  OrderDecisionDetailsView,
  OrderDecisionDetailsView$zodSchema,
} from "./orderdecisiondetailsview.js";
import {
  ReviewTicketView,
  ReviewTicketView$zodSchema,
} from "./reviewticketview.js";
import {
  RiskModelExternalResultView,
  RiskModelExternalResultView$zodSchema,
} from "./riskmodelexternalresultview.js";
import {
  RiskReviewStatus,
  RiskReviewStatus$zodSchema,
} from "./riskreviewstatus.js";
import {
  TransactionIndemnificationDecision,
  TransactionIndemnificationDecision$zodSchema,
} from "./transactionindemnificationdecision.js";
import {
  TransactionIndemnificationReason,
  TransactionIndemnificationReason$zodSchema,
} from "./transactionindemnificationreason.js";
import {
  TransactionProcessor,
  TransactionProcessor$zodSchema,
} from "./transactionprocessor.js";
import {
  TransactionSplitsView,
  TransactionSplitsView$zodSchema,
} from "./transactionsplitsview.js";
import {
  TransactionStatus,
  TransactionStatus$zodSchema,
} from "./transactionstatus.js";
import {
  TransactionType,
  TransactionType$zodSchema,
} from "./transactiontype.js";

export const TransactionViewViewStatus$zodSchema = z.enum([
  "not_viewed",
  "viewed",
  "viewing",
]);

export type TransactionViewViewStatus = z.infer<
  typeof TransactionViewViewStatus$zodSchema
>;

export type TransactionView = {
  amount?: AmountView | undefined;
  authorization?: CreditCardAuthorizationView | undefined;
  capture?: CaptureView | undefined;
  captures?: Array<CreditCardCaptureView> | undefined;
  credit?: CreditCardCreditView | undefined;
  date?: number | undefined;
  from_consumer?: ConsumerSelfView | undefined;
  from_credit_card?: CreditCardView | undefined;
  id?: string | undefined;
  indemnification_decision?: TransactionIndemnificationDecision | undefined;
  indemnification_reason?: TransactionIndemnificationReason | undefined;
  last4?: string | undefined;
  last_viewed_utc?: number | undefined;
  merchant_division?: MerchantDivisionSummaryView | undefined;
  merchant_order_number?: string | undefined;
  order_decision?: OrderDecisionDetailsView | undefined;
  processor?: TransactionProcessor | undefined;
  reference?: string | undefined;
  review_ticket?: ReviewTicketView | undefined;
  risk_insights?: RiskModelExternalResultView | undefined;
  risk_review_status?: RiskReviewStatus | undefined;
  risk_score?: number | undefined;
  splits?: Array<TransactionSplitsView> | undefined;
  status?: TransactionStatus | undefined;
  to_consumer?: ConsumerSelfView | undefined;
  to_credit_card?: CreditCardView | undefined;
  transaction_properties?: { [k: string]: string } | undefined;
  type?: TransactionType | undefined;
  void?: CreditCardVoidView | undefined;
  view_status?: TransactionViewViewStatus | undefined;
};

export const TransactionView$zodSchema: z.ZodType<
  TransactionView,
  z.ZodTypeDef,
  unknown
> = z.object({
  amount: AmountView$zodSchema.optional(),
  authorization: CreditCardAuthorizationView$zodSchema.optional(),
  capture: CaptureView$zodSchema.optional(),
  captures: z.array(CreditCardCaptureView$zodSchema).optional(),
  credit: CreditCardCreditView$zodSchema.optional(),
  date: z.number().int().optional(),
  from_consumer: ConsumerSelfView$zodSchema.optional(),
  from_credit_card: CreditCardView$zodSchema.optional(),
  id: z.string().optional(),
  indemnification_decision: TransactionIndemnificationDecision$zodSchema
    .optional(),
  indemnification_reason: TransactionIndemnificationReason$zodSchema.optional(),
  last4: z.string().optional(),
  last_viewed_utc: z.number().optional(),
  merchant_division: MerchantDivisionSummaryView$zodSchema.optional(),
  merchant_order_number: z.string().optional(),
  order_decision: OrderDecisionDetailsView$zodSchema.optional(),
  processor: TransactionProcessor$zodSchema.optional(),
  reference: z.string().optional(),
  review_ticket: ReviewTicketView$zodSchema.optional(),
  risk_insights: RiskModelExternalResultView$zodSchema.optional(),
  risk_review_status: RiskReviewStatus$zodSchema.optional(),
  risk_score: z.number().int().optional(),
  splits: z.array(TransactionSplitsView$zodSchema).optional(),
  status: TransactionStatus$zodSchema.optional(),
  to_consumer: ConsumerSelfView$zodSchema.optional(),
  to_credit_card: CreditCardView$zodSchema.optional(),
  transaction_properties: z.record(z.string()).optional(),
  type: TransactionType$zodSchema.optional(),
  view_status: TransactionViewViewStatus$zodSchema.optional(),
  void: CreditCardVoidView$zodSchema.optional(),
});
