/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Determines if item is a physical, digital, or bundled good, or if the good type is unknown.
 */
export const Type$zodSchema = z.enum([
  "bundled",
  "digital",
  "physical",
  "unknown",
]).describe(
  "Determines if item is a physical, digital, or bundled good, or if the good type is unknown.",
);

export type Type = z.infer<typeof Type$zodSchema>;
