/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ProfileView, ProfileView$zodSchema } from "./profileview.js";
import { UpdateProfile, UpdateProfile$zodSchema } from "./updateprofile.js";

export type UpdateAccountProfileSecurity = { OAuth: string; xAPIKey: string };

export const UpdateAccountProfileSecurity$zodSchema: z.ZodType<
  UpdateAccountProfileSecurity,
  z.ZodTypeDef,
  unknown
> = z.object({
  OAuth: z.string().describe(
    "Bolt utilizes the OAuth flow that developers can use to attain access to Bolt Account data via APIs.\n"
      + "For all APIs that require authorization, please provide your `access_token` returned from `/v1/oauth/token` via the basic auth bearer header `Authorization: bearer ${TOKEN}`.\n"
      + "[Read more about the OAuth token endpoint.](/api-bolt/#tag/OAuth)\n"
      + "",
  ),
  xAPIKey: z.string().describe(
    "Admins and Developers can obtain their Bolt API key from the Bolt Merchant Dashboard.",
  ),
});

export type UpdateAccountProfileRequest = {
  xPublishableKey?: string | undefined;
  update_profile?: UpdateProfile | undefined;
};

export const UpdateAccountProfileRequest$zodSchema: z.ZodType<
  UpdateAccountProfileRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  update_profile: UpdateProfile$zodSchema.optional(),
  xPublishableKey: z.string().describe(
    "The publicly viewable identifier used to identify a merchant division. This key is found in the Developer > API section of the Bolt Merchant Dashboard [RECOMMENDED].",
  ).optional(),
});

export type UpdateAccountProfileResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  profile_view?: ProfileView | undefined;
};

export const UpdateAccountProfileResponse$zodSchema: z.ZodType<
  UpdateAccountProfileResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  profile_view: ProfileView$zodSchema.optional(),
});
