/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ShopperMetadata,
  ShopperMetadata$zodSchema,
} from "./shoppermetadata.js";

/**
 * The profile fields that can be updated for a shopper.
 */
export type UpdateProfile = {
  first_name?: string | undefined;
  last_name?: string | undefined;
  metadata?: ShopperMetadata | null | undefined;
};

export const UpdateProfile$zodSchema: z.ZodType<
  UpdateProfile,
  z.ZodTypeDef,
  unknown
> = z.object({
  first_name: z.string().optional(),
  last_name: z.string().optional(),
  metadata: ShopperMetadata$zodSchema.nullable().optional(),
}).describe("The profile fields that can be updated for a shopper.");
