/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ErrorsBoltApiResponse,
  ErrorsBoltApiResponse$zodSchema,
} from "./errorsboltapiresponse.js";
import {
  TransactionDetails,
  TransactionDetails$zodSchema,
} from "./transactiondetails.js";
import {
  TransactionUpdateInput,
  TransactionUpdateInput$zodSchema,
} from "./transactionupdateinput.js";

export type UpdateTransactionRequest = {
  REFERENCE: string;
  idempotencyKey?: string | undefined;
  transaction_update_input?: TransactionUpdateInput | undefined;
};

export const UpdateTransactionRequest$zodSchema: z.ZodType<
  UpdateTransactionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  REFERENCE: z.string().describe(
    "This is the Bolt transaction reference. (ex. N7Y3-NFKC-VFRF)",
  ),
  idempotencyKey: z.string().describe(
    "A key created by merchants that ensures `POST` and `PATCH` requests are only performed once. [Read more about Idempotent Requests here](/developers/references/idempotency/).",
  ).optional(),
  transaction_update_input: TransactionUpdateInput$zodSchema.optional(),
});

export type UpdateTransactionResponse = {
  ContentType: string;
  StatusCode: number;
  RawResponse: Response;
  transaction_details?: TransactionDetails | undefined;
  errors_bolt_api_response?: ErrorsBoltApiResponse | undefined;
};

export const UpdateTransactionResponse$zodSchema: z.ZodType<
  UpdateTransactionResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ContentType: z.string(),
  RawResponse: z.instanceof(Response),
  StatusCode: z.number().int(),
  errors_bolt_api_response: ErrorsBoltApiResponse$zodSchema.optional(),
  transaction_details: TransactionDetails$zodSchema.optional(),
});
