/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type UserIdentity = {
  first_name?: string | undefined;
  last_name?: string | undefined;
};

export const UserIdentity$zodSchema: z.ZodType<
  UserIdentity,
  z.ZodTypeDef,
  unknown
> = z.object({
  first_name: z.string().optional(),
  last_name: z.string().optional(),
});
