/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The object containing key lookup IDs associated with the shopper's account, such as the unique email address and phone number.
 */
export type UserIdentifier = {
  artifact?: string | undefined;
  email?: string | undefined;
  email_id?: string | undefined;
  phone: string;
  phone_id?: string | undefined;
};

export const UserIdentifier$zodSchema: z.ZodType<
  UserIdentifier,
  z.ZodTypeDef,
  unknown
> = z.object({
  artifact: z.string().optional(),
  email: z.string().optional(),
  email_id: z.string().optional(),
  phone: z.string(),
  phone_id: z.string().optional(),
}).describe(
  "The object containing key lookup IDs associated with the shopper's account, such as the unique email address and phone number.",
);
