/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type V1AccountsView = { has_bolt_account?: boolean | undefined };

export const V1AccountsView$zodSchema: z.ZodType<
  V1AccountsView,
  z.ZodTypeDef,
  unknown
> = z.object({
  has_bolt_account: z.boolean().optional(),
});
