/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Subscribe to a group of events.
 *
 * @remarks
 * `all`: subscribe to all existing and future event types
 */
export const WebhookEventGroup$zodSchema = z.enum([
  "all",
  "null",
]).describe(
  "Subscribe to a group of events.\n"
    + "`all`: subscribe to all existing and future event types\n"
    + "",
);

export type WebhookEventGroup = z.infer<typeof WebhookEventGroup$zodSchema>;
