/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  WebhookEventGroup,
  WebhookEventGroup$zodSchema,
} from "./webhookeventgroup.js";
import { WebhooksType, WebhooksType$zodSchema } from "./webhookstype.js";

export type Webhook = {
  created_at: number;
  event_group?: WebhookEventGroup | null | undefined;
  events?: Array<WebhooksType> | null | undefined;
  url: string;
  webhook_id: string;
};

export const Webhook$zodSchema: z.ZodType<Webhook, z.ZodTypeDef, unknown> = z
  .object({
    created_at: z.number().int(),
    event_group: WebhookEventGroup$zodSchema.nullable().optional(),
    events: z.array(WebhooksType$zodSchema).nullable().optional(),
    url: z.string(),
    webhook_id: z.string(),
  });
