/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * [Webhook events](https://help.bolt.com/developers/guides/webhooks/#transaction-hook-types) that trigger a notification to the URL.  **Note**:`newsletter_subscription` is only for merchant use cases.
 *
 * @remarks
 */
export const WebhooksType$zodSchema = z.enum([
  "payment",
  "credit",
  "capture",
  "void",
  "auth",
  "pending",
  "rejected_irreversible",
  "rejected_reversible",
  "failed_payment",
  "newsletter_subscription",
  "risk_insights",
  "credit_card_deleted",
]).describe(
  "[Webhook events](https://help.bolt.com/developers/guides/webhooks/#transaction-hook-types) that trigger a notification to the URL.  **Note**:`newsletter_subscription` is only for merchant use cases.\n"
    + "",
);

export type WebhooksType = z.infer<typeof WebhooksType$zodSchema>;
